// Eigener Fragenkatalog. Einfach erweitern – jede Kategorie ist ein Array.

module.exports = {
  // Ich hab noch nie – wer es getan hat, trinkt 1
  nie: [
    "Ich hab noch nie in der Öffentlichkeit geweint.",
    "Ich hab noch nie ein Date vorzeitig abgebrochen.",
    "Ich hab noch nie ein Geschenk weiterverschenkt.",
    "Ich hab noch nie so getan, als würde ich jemanden auf der Straße nicht erkennen.",
    "Ich hab noch nie eine ganze Serie an einem Wochenende durchgeschaut.",
    "Ich hab noch nie eine Nachricht an die falsche Person geschickt.",
    "Ich hab noch nie den Wecker fünfmal hintereinander weggedrückt.",
    "Ich hab noch nie Essen bestellt, obwohl der Kühlschrank voll war.",
    "Ich hab noch nie den letzten Zug oder Bus verpasst und bin zu Fuß nach Hause.",
    "Ich hab noch nie jemanden nur wegen seines Hundes angesprochen.",
    "Ich hab noch nie meinen eigenen Namen gegoogelt.",
    "Ich hab noch nie ein Gerät repariert, indem ich es aus- und wieder eingeschaltet habe, und es dann als Fachwissen verkauft.",
    "Ich hab noch nie den Kellner mit 'Danke, dir auch' verabschiedet.",
    "Ich hab noch nie beim Karaoke den Text komplett vergessen.",
    "Ich hab noch nie mehr als 24 Stunden am Stück kein Handy benutzt.",
    "Ich hab noch nie auf einer Party heimlich früher den Heimweg angetreten.",
    "Ich hab noch nie einem Schwarm über zwei Wochen lang nicht geantwortet.",
    "Ich hab noch nie eine Prüfung ohne jede Vorbereitung geschrieben.",
    "Ich hab noch nie ein Selfie 20 Mal wiederholt, bevor ich es gepostet habe.",
    "Ich hab noch nie den Geburtstag eines guten Freundes vergessen.",
    "Ich hab noch nie mit Vollgas 'Ja' gesagt und keine Ahnung gehabt, wozu.",
    "Ich hab noch nie eine Pflanze durch Vergessen getötet.",
    "Ich hab noch nie so getan, als hätte ich ein Buch gelesen.",
    "Ich hab noch nie in einem Meeting oder Kurs geschlafen.",
    "Ich hab noch nie Kleidung getragen, die eigentlich in die Wäsche gehörte.",
  ],

  // Wer würde eher – meistgewählte Person trinkt 2
  wer: [
    "Wer würde eher bei einer Zombie-Apokalypse als Erstes draufgehen?",
    "Wer würde eher aus Versehen ein Haus anzünden?",
    "Wer würde eher ohne Handy eine Woche in der Wildnis überleben?",
    "Wer würde eher eine Million Euro in einem Jahr verprassen?",
    "Wer würde eher bei einem Blind Date einfach abhauen?",
    "Wer würde eher in einer Reality-Show landen?",
    "Wer würde eher ein Lied an der Bar dem DJ aufzwingen?",
    "Wer würde eher heimlich Karaoke im Auto singen und dabei erwischt werden?",
    "Wer würde eher eine Diät nach zwei Tagen abbrechen?",
    "Wer würde eher versehentlich seinen Chef mit 'Mama' anreden?",
    "Wer würde eher in einer fremden Stadt hoffnungslos verloren gehen?",
    "Wer würde eher nach einem Kater 'nie wieder Alkohol' sagen und es am selben Abend brechen?",
    "Wer würde eher einen Tiktok-Trend voll ernst nehmen?",
    "Wer würde eher ohne Ticket in der Bahn erwischt werden?",
    "Wer würde eher einen Streit mit einem Fremden im Internet anfangen?",
    "Wer würde eher beim Kochen die Rauchmelder auslösen?",
    "Wer würde eher einen Heiratsantrag auf einem Stadionscreen machen?",
    "Wer würde eher das Geburtstagskind auf der eigenen Party vergessen?",
    "Wer würde eher nachts um drei noch eine Pizza bestellen?",
    "Wer würde eher ein Tattoo vom Namen des Partners haben?",
    "Wer würde eher Bürgermeister werden?",
    "Wer würde eher bei einem Quiz alles wissen und trotzdem verlieren?",
    "Wer würde eher einen Roadtrip ohne Plan starten?",
    "Wer würde eher heulen, wenn der Lieblingsverein absteigt?",
  ],

  // Schätzfragen – wer am weitesten daneben liegt, trinkt 3; zweitweiteste trinkt 1
  schaetz: [
    { q: "Wie viele Knochen hat ein erwachsener Mensch?", a: 206, unit: "" },
    { q: "Wie hoch ist der Eiffelturm in Metern (mit Antenne)?", a: 330, unit: "m" },
    { q: "Wie viele Länder gibt es in Afrika?", a: 54, unit: "" },
    { q: "Wie viele Tasten hat ein Klavier?", a: 88, unit: "" },
    { q: "Wie lang ist der Rhein in Kilometern?", a: 1233, unit: "km" },
    { q: "Wie viele Zähne hat ein Erwachsener normalerweise (mit Weisheitszähnen)?", a: 32, unit: "" },
    { q: "Wie viele Einwohner hat Berlin ungefähr (in Millionen)?", a: 3.9, unit: "Mio" },
    { q: "Wie viele Minuten dauert ein Marathon-Weltrekord ungefähr?", a: 120, unit: "min" },
    { q: "Wie viele Sekunden hat ein Tag?", a: 86400, unit: "s" },
    { q: "Wie viel wiegt ein Elefantenbulle ungefähr (in Kilogramm)?", a: 6000, unit: "kg" },
    { q: "Wie viele Bundesländer hat Deutschland?", a: 16, unit: "" },
    { q: "Wie viel Prozent der Erdoberfläche sind Wasser?", a: 71, unit: "%" },
    { q: "Wie hoch ist der Mount Everest in Metern?", a: 8849, unit: "m" },
    { q: "Wie viele Spieler stehen bei einem Fußballspiel gleichzeitig auf dem Platz (beide Teams)?", a: 22, unit: "" },
    { q: "Wie viele Herzschläge hat ein Mensch etwa pro Tag?", a: 100000, unit: "" },
    { q: "Wie viele Grad hat ein Kreis?", a: 360, unit: "°" },
    { q: "Wie viele Monde hat der Jupiter (bekannte, ungefähr)?", a: 95, unit: "" },
    { q: "Wie viele Kalorien hat ein Liter Bier ungefähr?", a: 430, unit: "kcal" },
    { q: "Wie viele Kilometer sind es Luftlinie von Berlin nach München?", a: 504, unit: "km" },
    { q: "Wie viel Prozent Alkohol hat ein klassischer Wodka?", a: 40, unit: "%" },
    { q: "Wie viele Sterne hat die Flagge der EU?", a: 12, unit: "" },
    { q: "Wie viele Tage hat ein Schaltjahr?", a: 366, unit: "" },
    { q: "In welchem Jahr fiel die Berliner Mauer?", a: 1989, unit: "" },
    { q: "Wie viele Karten hat ein Skatblatt?", a: 32, unit: "" },
  ],

  // Wahrheit oder Pflicht – zufällige Person, Verweigern = 3 Schlücke
  wahrheit: [
    "Was war dein peinlichster Moment in den letzten zwölf Monaten?",
    "Wen in dieser Runde würdest du als Erstes auf eine einsame Insel mitnehmen?",
    "Welche Lüge erzählst du am häufigsten?",
    "Was war das Kindischste, das du diese Woche gemacht hast?",
    "Welchen Song hörst du heimlich gerne, obwohl er dir peinlich ist?",
    "Was ist der seltsamste Ort, an dem du eingeschlafen bist?",
    "Wen aus der Runde hast du schon mal auf stumm geschaltet?",
    "Was ist das Teuerste, das du je kaputt gemacht hast?",
    "Welche Angewohnheit von dir nervt deine Freunde am meisten?",
    "Was war dein schlimmster Kater und wie kam es dazu?",
    "Was hast du als letztes bei Google gesucht?",
    "Welche Ausrede hast du benutzt, um eine Einladung abzusagen?",
    "Was ist dein unbeliebtestes Essen, das du trotzdem aus Höflichkeit gegessen hast?",
    "Wem würdest du am liebsten mal so richtig die Meinung sagen?",
    "Was ist dein größter Guilty-Pleasure-Film?",
  ],
  pflicht: [
    "Sprich bis zur nächsten Runde nur in Reimen.",
    "Lass dir vom Spieler links neben dir eine neue Frisur machen.",
    "Zeig der Runde das letzte Foto in deiner Galerie.",
    "Mach 15 Kniebeugen, während du die Nationalhymne summst.",
    "Ruf einen Kontakt an und sing ihm 'Happy Birthday', egal ob er Geburtstag hat.",
    "Trage bis zum Ende des Spiels einen Gegenstand als Hut.",
    "Sprich zwei Runden lang mit dem Akzent deiner Wahl.",
    "Imitiere einen Mitspieler, bis die Runde ihn errät.",
    "Poste eine Story mit deinem schlechtesten Gesichtsausdruck.",
    "Lass dir die Augen verbinden und errate, was dir ins Glas geschüttet wurde.",
    "Tanze 30 Sekunden ohne Musik.",
    "Mach ein Kompliment an jede Person in der Runde – ohne dich zu wiederholen.",
    "Sprich bis zur nächsten Runde in der dritten Person über dich.",
    "Schick deiner letzten WhatsApp-Kontaktperson einen Gute-Nacht-Gruß mit Herz.",
    "Erzähl einen Witz. Lacht keiner, trinkst du 2.",
  ],

  // Entweder oder – die Minderheit trinkt 1
  oder: [
    ["Bier", "Wein"],
    ["Sommer", "Winter"],
    ["Netflix-Abend", "Clubnacht"],
    ["Pizza", "Burger"],
    ["Strand", "Berge"],
    ["Frühaufsteher", "Nachteule"],
    ["Hund", "Katze"],
    ["Fliegen können", "Unsichtbar sein"],
    ["Nie wieder Handy", "Nie wieder Auto"],
    ["Kaffee", "Tee"],
    ["Süß", "Salzig"],
    ["Zug", "Flugzeug"],
    ["Zehn Jahre in die Zukunft", "Zehn Jahre in die Vergangenheit"],
    ["Immer laut reden", "Immer flüstern"],
    ["Sushi", "Döner"],
    ["Gaming", "Sport"],
    ["Lieber immer zu früh", "Lieber immer zu spät"],
    ["Kochen", "Bestellen"],
    ["Meer ohne Netz", "Stadt ohne Schlaf"],
    ["Cocktail", "Shot"],
  ],
};
