// Eigener Fragenkatalog – 1011 Einträge. Einfach erweitern, Kommas nicht vergessen.
// Schätzfrage: { q, a: Zahl, unit }   Trivia: { q, o: [4 Antworten], c: Index der richtigen (0-3) }

module.exports = {
  // Ich hab noch nie – wer es getan hat, trinkt 1
  nie: [
    "Ich hab noch nie in der Öffentlichkeit geweint.",
    "Ich hab noch nie ein Date vorzeitig abgebrochen.",
    "Ich hab noch nie ein Geschenk weiterverschenkt.",
    "Ich hab noch nie so getan, als würde ich jemanden auf der Straße nicht erkennen.",
    "Ich hab noch nie eine ganze Serie an einem Wochenende durchgeschaut.",
    "Ich hab noch nie eine Nachricht an die falsche Person geschickt.",
    "Ich hab noch nie den Wecker fünfmal hintereinander weggedrückt.",
    "Ich hab noch nie Essen bestellt, obwohl der Kühlschrank voll war.",
    "Ich hab noch nie den letzten Bus verpasst und bin zu Fuß nach Hause.",
    "Ich hab noch nie jemanden nur wegen seines Hundes angesprochen.",
    "Ich hab noch nie meinen eigenen Namen gegoogelt.",
    "Ich hab noch nie den Kellner mit \"Danke, dir auch\" verabschiedet.",
    "Ich hab noch nie beim Karaoke den Text komplett vergessen.",
    "Ich hab noch nie mehr als 24 Stunden am Stück kein Handy benutzt.",
    "Ich hab noch nie auf einer Party heimlich früher den Heimweg angetreten.",
    "Ich hab noch nie eine Prüfung ohne jede Vorbereitung geschrieben.",
    "Ich hab noch nie ein Selfie 20 Mal wiederholt, bevor ich es gepostet habe.",
    "Ich hab noch nie den Geburtstag eines guten Freundes vergessen.",
    "Ich hab noch nie eine Pflanze durch Vergessen getötet.",
    "Ich hab noch nie so getan, als hätte ich ein Buch gelesen.",
    "Ich hab noch nie in einem Meeting oder einer Vorlesung geschlafen.",
    "Ich hab noch nie Kleidung getragen, die eigentlich in die Wäsche gehörte.",
    "Ich hab noch nie im Kino geschlafen.",
    "Ich hab noch nie einen Ex auf Social Media gestalkt.",
    "Ich hab noch nie einen Kater mit einem Bier bekämpft.",
    "Ich hab noch nie mich krank gemeldet, obwohl ich fit war.",
    "Ich hab noch nie in einem Aufzug gepupst und jemand anderen angeschaut.",
    "Ich hab noch nie mein Handy im Klo versenkt.",
    "Ich hab noch nie einen Film gesehen, ohne das Ende zu verstehen, und trotzdem mitgeredet.",
    "Ich hab noch nie beim Sport so getan, als würde ich mich anstrengen.",
    "Ich hab noch nie etwas im Laden probiert und nicht bezahlt.",
    "Ich hab noch nie jemandem zum Geburtstag gratuliert, weil Facebook es gesagt hat.",
    "Ich hab noch nie mit dem Handy in der Hand nach dem Handy gesucht.",
    "Ich hab noch nie eine Fremdsprache vorgetäuscht.",
    "Ich hab noch nie ein Foto von meinem Essen gemacht, bevor ich gegessen habe.",
    "Ich hab noch nie mich beim Kochen geschnitten.",
    "Ich hab noch nie in einem Restaurant das Trinkgeld vergessen.",
    "Ich hab noch nie den ganzen Tag im Schlafanzug verbracht.",
    "Ich hab noch nie länger als eine Stunde geduscht.",
    "Ich hab noch nie einen Tag lang nur Süßigkeiten gegessen.",
    "Ich hab noch nie in fremden Badezimmern die Schränke durchsucht.",
    "Ich hab noch nie mich bei einem Spiel absichtlich verlieren lassen.",
    "Ich hab noch nie ein Reality-TV-Format heimlich gemocht.",
    "Ich hab noch nie einen Kinderfilm ohne Kinder geschaut.",
    "Ich hab noch nie länger als drei Tage dieselbe Jogginghose getragen.",
    "Ich hab noch nie im Auto gesungen und wurde an der Ampel erwischt.",
    "Ich hab noch nie einen Fahrradreifen geflickt.",
    "Ich hab noch nie beim Vorstellungsgespräch gelogen.",
    "Ich hab noch nie auf einem Konzert die falsche Band gefeiert.",
    "Ich hab noch nie ein Parkticket ignoriert.",
    "Ich hab noch nie mit Absicht die Straßenseite gewechselt, um jemanden nicht zu treffen.",
    "Ich hab noch nie eine Beziehung per Nachricht beendet.",
    "Ich hab noch nie so getan, als würde ich telefonieren.",
    "Ich hab noch nie beim Netflix-Schauen die Frage \"Schaust du noch?\" beantworten müssen.",
    "Ich hab noch nie im Zug den falschen Sitzplatz besetzt und es einfach durchgezogen.",
    "Ich hab noch nie ein Zimmer nur aufgeräumt, weil Besuch kam.",
    "Ich hab noch nie mich für einen Termin extra hübsch gemacht, der dann online war.",
    "Ich hab noch nie meine Eltern nach Geld gefragt, obwohl ich längst arbeite.",
    "Ich hab noch nie beim Friseur \"ja, super\" gesagt und zuhause geheult.",
    "Ich hab noch nie eine Nacht komplett durchgemacht.",
    "Ich hab noch nie ein Trinkspiel gewonnen.",
    "Ich hab noch nie mich an einer Kasse vorgedrängelt.",
    "Ich hab noch nie eine Rechnung \"vergessen\" zu bezahlen.",
    "Ich hab noch nie in einem Club auf der Toilette Freundschaft geschlossen.",
    "Ich hab noch nie den Namen einer Person vergessen, mit der ich gerade sprach.",
    "Ich hab noch nie etwas online bestellt und beim Auspacken vergessen, was es war.",
    "Ich hab noch nie ein Tinder-Date gehabt.",
    "Ich hab noch nie die Lieblingsserie eines Freundes schlechtgeredet, ohne sie gesehen zu haben.",
    "Ich hab noch nie eine Karaoke-Bar nüchtern betreten.",
    "Ich hab noch nie einen Antrag auf einem Amt dreimal ausfüllen müssen.",
    "Ich hab noch nie eine Diät am ersten Tag abgebrochen.",
    "Ich hab noch nie aus Versehen jemanden zurückgerufen.",
    "Ich hab noch nie mit einer Katze länger geredet als mit Menschen an dem Tag.",
    "Ich hab noch nie in einem Aufzug die Tür-zu-Taste gedrückt, als jemand kam.",
    "Ich hab noch nie so getan, als kenne ich den Song, den alle mitsingen.",
    "Ich hab noch nie eine Serie nur wegen eines Schauspielers geschaut.",
    "Ich hab noch nie den Weihnachtsbaum bis Februar stehen lassen.",
    "Ich hab noch nie etwas im Second-Hand-Laden zu teuer gekauft.",
    "Ich hab noch nie den Herd angelassen und bin gegangen.",
    "Ich hab noch nie bei einem Streit den Fernseher lauter gemacht.",
    "Ich hab noch nie in einem Hotel etwas mitgehen lassen, das keine Seife war.",
    "Ich hab noch nie einen Vertrag unterschrieben, ohne ihn zu lesen.",
    "Ich hab noch nie Fastfood zum Frühstück gegessen.",
    "Ich hab noch nie mich mit einer WhatsApp-Gruppe verrannt und alle stummgeschaltet.",
    "Ich hab noch nie so getan, als hätte ich Hunger, nur um mitzuessen.",
    "Ich hab noch nie mein Passwort auf einen Zettel am Monitor geschrieben.",
    "Ich hab noch nie jemanden mit \"Kennen wir uns?\" angesprochen, um zu flirten.",
    "Ich hab noch nie heimlich im Auto geweint.",
    "Ich hab noch nie einen Song aus Scham gelöscht, den ich gerne höre.",
    "Ich hab noch nie eine Wette verloren und nicht bezahlt.",
    "Ich hab noch nie einen Mitbewohner beim Essen beklaut.",
    "Ich hab noch nie ein Geschenk gekauft und selbst behalten.",
    "Ich hab noch nie im Supermarkt an der Kasse gemerkt, dass das Geld nicht reicht.",
    "Ich hab noch nie beim Wandern nach fünf Minuten umgedreht.",
    "Ich hab noch nie bei einer Hochzeit den falschen Namen gerufen.",
    "Ich hab noch nie ein Handy-Foto von einem Fremden gemacht.",
    "Ich hab noch nie Karaoke mit vollem Einsatz gesungen.",
    "Ich hab noch nie Sport getrieben, nur um danach zu essen.",
    "Ich hab noch nie das Kino-Popcorn vor dem Filmstart aufgegessen.",
    "Ich hab noch nie in einer Sauna gewesen und es gehasst.",
    "Ich hab noch nie einen ganzen Kuchen alleine gegessen.",
    "Ich hab noch nie ein Taxi bestellt, obwohl es fünf Minuten zu Fuß waren.",
    "Ich hab noch nie das Datum vergessen und ein Jahr zu früh unterschrieben.",
    "Ich hab noch nie in einem Fitnessstudio gewesen und nur geduscht.",
    "Ich hab noch nie länger als zwei Stunden auf ein Paket gewartet und es dann verpasst.",
    "Ich hab noch nie in der Bahn den Fenstersitz gegen ein Kind verteidigt.",
    "Ich hab noch nie ein Gerücht verbreitet, das ich erfunden habe.",
    "Ich hab noch nie mich nachts verlaufen und den Weg per Sternen gesucht.",
    "Ich hab noch nie in fremden Ländern deutsches Essen bestellt.",
    "Ich hab noch nie in einem Restaurant reklamiert.",
    "Ich hab noch nie geschnarcht und es geleugnet.",
    "Ich hab noch nie bei einem Quiz alle Fragen falsch gehabt.",
    "Ich hab noch nie einen Wohnungsschlüssel verloren.",
    "Ich hab noch nie das gleiche Outfit an zwei Tagen hintereinander bei der Arbeit getragen.",
    "Ich hab noch nie ein Auto-Rad gewechselt.",
    "Ich hab noch nie eine Lebensmittelvergiftung gehabt.",
    "Ich hab noch nie ein Haustier auf den Namen eines Promis getauft.",
    "Ich hab noch nie ein Foto retuschiert.",
    "Ich hab noch nie so getan, als sei mein Handy leer.",
    "Ich hab noch nie mich in einem Fahrstuhl verspiegelt und gepost.",
    "Ich hab noch nie länger als 20 Minuten nach einem Parkplatz gesucht.",
    "Ich hab noch nie im Bett gegessen.",
    "Ich hab noch nie Krümel im Bett einfach zur Seite geschoben.",
    "Ich hab noch nie mich im Bett komplett angezogen ausgeruht und dann geschlafen.",
    "Ich hab noch nie eine Beerdigung geschwänzt.",
    "Ich hab noch nie einen Klassentreffen-Termin absichtlich verpasst.",
    "Ich hab noch nie mit Vollgas eine Kurve unterschätzt.",
    "Ich hab noch nie den Duschvorhang benutzt, um Wasser zu trinken.",
    "Ich hab noch nie länger als eine Woche keinen Salat gegessen.",
    "Ich hab noch nie eine Fernbeziehung gehabt.",
    "Ich hab noch nie aus Faulheit die Milch ohne Müsli gegessen.",
    "Ich hab noch nie bei einem Spiel geschummelt und gewonnen.",
    "Ich hab noch nie meinem Chef gesagt, was ich wirklich denke.",
    "Ich hab noch nie in einem Bewerbungsgespräch die Firma verwechselt.",
    "Ich hab noch nie ein Tattoo bereut.",
    "Ich hab noch nie nach Mitternacht eine SMS an einen Ex geschickt.",
    "Ich hab noch nie einen Song für jemanden geschrieben.",
    "Ich hab noch nie ein Buch nach 20 Seiten aufgegeben.",
    "Ich hab noch nie mein eigenes Kochen nicht gegessen.",
    "Ich hab noch nie so getan, als hätte ich die Nachricht nicht gelesen.",
    "Ich hab noch nie das WLAN vom Nachbarn benutzt.",
    "Ich hab noch nie mein Zimmer nur unter dem Bett geputzt.",
    "Ich hab noch nie ein Möbelstück falsch zusammengebaut und so gelassen.",
    "Ich hab noch nie in einer Bar den Schlussakkord mitgesungen.",
    "Ich hab noch nie im Kino den Film verwechselt und geblieben.",
    "Ich hab noch nie ein Auto vollgetankt und die Rechnung vergessen.",
    "Ich hab noch nie einen Tag lang nur Kaffee getrunken.",
    "Ich hab noch nie einen Handwerker gerufen, weil ich den Stecker nicht sah.",
    "Ich hab noch nie mein Geburtstagsgeschenk selbst gekauft.",
    "Ich hab noch nie mit einem Fremden auf einem Konzert getanzt.",
    "Ich hab noch nie das Ende einer Serie gespoilert bekommen und trotzdem weitergeschaut.",
    "Ich hab noch nie den ganzen Tag im Bett verbracht ohne krank zu sein.",
    "Ich hab noch nie den Balkon als Kühlschrank benutzt.",
    "Ich hab noch nie mein Handy auf dem Autodach vergessen und bin losgefahren.",
    "Ich hab noch nie einen Freund bei einer Ausrede verraten.",
    "Ich hab noch nie ein Foto in der Umkleidekabine gemacht.",
    "Ich hab noch nie beim Schummeln in der Schule erwischt worden.",
    "Ich hab noch nie in einer Stadt gewohnt, in der ich niemanden kannte.",
    "Ich hab noch nie mit meinem Haustier in einem Bett geschlafen.",
    "Ich hab noch nie mit dem Kopf gegen eine Glastür gelaufen.",
    "Ich hab noch nie das Passwort meiner Eltern für Netflix benutzt.",
    "Ich hab noch nie nach dem Gym direkt zu McDonald's gefahren.",
    "Ich hab noch nie so getan, als hätte ich meinen Schlüssel vergessen, um zu bleiben.",
    "Ich hab noch nie eine Nacht im Auto geschlafen.",
    "Ich hab noch nie in einem Meeting mein eigenes Handy klingeln hören.",
    "Ich hab noch nie etwas Geliehenes nie zurückgegeben.",
    "Ich hab noch nie in einem Spiel mein Team absichtlich untergehen lassen.",
    "Ich hab noch nie in einem Land ohne Rückflugticket gewesen.",
    "Ich hab noch nie mich mit dem Lieferdienst angefreundet.",
    "Ich hab noch nie zu einer Party gegangen, ohne die Gastgeber zu kennen.",
    "Ich hab noch nie ein Musikinstrument gekauft und nie gespielt.",
    "Ich hab noch nie eine Nachricht mit \"ok\" beantwortet und einen Streit ausgelöst.",
    "Ich hab noch nie ein Gerät geschüttelt, bis es lief.",
    "Ich hab noch nie mich für eine Runde Bowling verletzt.",
    "Ich hab noch nie mit meinem Nachbarn über Musiklautstärke gestritten.",
    "Ich hab noch nie so getan, als sei ich vegan.",
    "Ich hab noch nie an einem Buffet die Regeln überschritten.",
    "Ich hab noch nie einen Schneemann mit einem Bier in der Hand gebaut.",
    "Ich hab noch nie im Supermarkt jemandem hinterhergelaufen, weil ich dachte, es sei ein Freund.",
    "Ich hab noch nie in der Bahn eingeschlafen und zu weit gefahren.",
    "Ich hab noch nie mein Fahrrad falsch abgeschlossen und es war weg.",
    "Ich hab noch nie den Heimweg vom Club nicht mehr gewusst.",
    "Ich hab noch nie den Kellner mit Namen angesprochen, der falsch war.",
    "Ich hab noch nie länger als drei Monate ein Abo nicht gekündigt.",
    "Ich hab noch nie eine Bewertung unter falschem Namen geschrieben.",
    "Ich hab noch nie mit jemandem geflirtet, um Freibier zu bekommen.",
    "Ich hab noch nie den Sonnenbrand mit Sonnencreme nachträglich behandelt.",
    "Ich hab noch nie ein Video von mir selbst geschaut und es gehasst.",
    "Ich hab noch nie das Wort \"Deadline\" zu ernst genommen.",
    "Ich hab noch nie ein Rezept geändert und es bereut.",
    "Ich hab noch nie im Ausland Deutsche gemieden.",
    "Ich hab noch nie so getan, als hätte ich Glückwünsche vergessen, um nicht anzurufen.",
    "Ich hab noch nie den Kühlschrank aus Langeweile geöffnet und wieder geschlossen.",
    "Ich hab noch nie ein Selfie auf einer Beerdigung gemacht.",
    "Ich hab noch nie jemanden nach seinem Namen gefragt, obwohl wir uns seit Jahren kennen.",
    "Ich hab noch nie ein Musikfestival ohne Ticket besucht.",
    "Ich hab noch nie das Trinkgeld aus Versehen zu hoch gegeben.",
    "Ich hab noch nie mich beim Zähneputzen mit Duschgel vertan.",
    "Ich hab noch nie mit einem Bus in die falsche Richtung gefahren.",
    "Ich hab noch nie das Geschirr eine Woche stehen lassen.",
    "Ich hab noch nie einen Streit über Ananas auf Pizza angefangen.",
    "Ich hab noch nie den Fahrstuhl mit jemandem geteilt, den ich vermeiden wollte.",
  ],

  // Wer würde eher – meistgewählte Person trinkt 2
  wer: [
    "Wer würde eher bei einer Zombie-Apokalypse als Erstes draufgehen?",
    "Wer würde eher aus Versehen ein Haus anzünden?",
    "Wer würde eher ohne Handy eine Woche in der Wildnis überleben?",
    "Wer würde eher eine Million Euro in einem Jahr verprassen?",
    "Wer würde eher bei einem Blind Date einfach abhauen?",
    "Wer würde eher in einer Reality-Show landen?",
    "Wer würde eher dem DJ ein Lied aufzwingen?",
    "Wer würde eher heimlich Karaoke im Auto singen und dabei erwischt werden?",
    "Wer würde eher eine Diät nach zwei Tagen abbrechen?",
    "Wer würde eher den Chef versehentlich mit \"Mama\" anreden?",
    "Wer würde eher in einer fremden Stadt hoffnungslos verloren gehen?",
    "Wer würde eher nach einem Kater \"nie wieder\" sagen und es am selben Abend brechen?",
    "Wer würde eher einen TikTok-Trend voll ernst nehmen?",
    "Wer würde eher ohne Ticket in der Bahn erwischt werden?",
    "Wer würde eher einen Streit mit einem Fremden im Internet anfangen?",
    "Wer würde eher beim Kochen den Rauchmelder auslösen?",
    "Wer würde eher einen Heiratsantrag auf einem Stadionscreen machen?",
    "Wer würde eher das Geburtstagskind auf der eigenen Party vergessen?",
    "Wer würde eher nachts um drei noch eine Pizza bestellen?",
    "Wer würde eher ein Tattoo vom Namen des Partners haben?",
    "Wer würde eher Bürgermeister werden?",
    "Wer würde eher bei einem Quiz alles wissen und trotzdem verlieren?",
    "Wer würde eher einen Roadtrip ohne Plan starten?",
    "Wer würde eher heulen, wenn der Lieblingsverein absteigt?",
    "Wer würde eher im Lotto gewinnen und es geheim halten?",
    "Wer würde eher auf einer Hochzeit die Braut versehentlich beleidigen?",
    "Wer würde eher ein Wochenende komplett verschlafen?",
    "Wer würde eher als Erstes in eine Sekte geraten?",
    "Wer würde eher den Kühlschrank leer essen, bevor der Besuch kommt?",
    "Wer würde eher im Urlaub den Pass verlieren?",
    "Wer würde eher eine Karriere als Influencer starten?",
    "Wer würde eher im Flugzeug mit dem Sitznachbarn Freundschaft schließen?",
    "Wer würde eher sich mit dem Nachbarn wegen einer Hecke anlegen?",
    "Wer würde eher auf einer Party in der Küche hängen bleiben?",
    "Wer würde eher den Kellner nach einem Date fragen?",
    "Wer würde eher einen Marathon laufen?",
    "Wer würde eher mit 40 noch bei den Eltern wohnen?",
    "Wer würde eher auf einem Festival das Zelt nicht mehr finden?",
    "Wer würde eher aus Versehen die ganze Firma per Mail beleidigen?",
    "Wer würde eher eine Katze nach einem Essen benennen?",
    "Wer würde eher bei einem Vorstellungsgespräch eine Lüge auffliegen lassen?",
    "Wer würde eher in der Bahn laut telefonieren?",
    "Wer würde eher einen Fremden im Club anschreien?",
    "Wer würde eher beim Wandern einen Berg unterschätzen?",
    "Wer würde eher den eigenen Hochzeitstag vergessen?",
    "Wer würde eher ein Haustier vom Tierheim spontan mitnehmen?",
    "Wer würde eher in einer Serie als Bösewicht besetzt werden?",
    "Wer würde eher ein Auto beim Einparken zerkratzen und wegfahren?",
    "Wer würde eher ein Buch schreiben?",
    "Wer würde eher den eigenen Geburtstag drei Tage lang feiern?",
    "Wer würde eher ein Konzert nur wegen der Getränke besuchen?",
    "Wer würde eher in Vegas heiraten?",
    "Wer würde eher eine Konferenz nur wegen des Buffets besuchen?",
    "Wer würde eher mitten im Film das Ende googeln?",
    "Wer würde eher in einem Escape Room in Panik geraten?",
    "Wer würde eher heimlich die Musik im Auto von anderen wechseln?",
    "Wer würde eher ein Selfie mit einem Promi machen und ihn nicht erkennen?",
    "Wer würde eher auf einem Date über den Ex reden?",
    "Wer würde eher den Namen des Dates vergessen?",
    "Wer würde eher Berufsschauspieler werden?",
    "Wer würde eher einen Preis für Faulheit gewinnen?",
    "Wer würde eher in einem Kaufhaus eingeschlossen werden und es genießen?",
    "Wer würde eher den letzten Schluck aus jeder Flasche nehmen?",
    "Wer würde eher die falsche Person per Sprachnachricht beleidigen?",
    "Wer würde eher am Strand von Möwen bestohlen werden?",
    "Wer würde eher einen Fußballverein gründen?",
    "Wer würde eher vor lauter Übermut aus einem Taxi springen?",
    "Wer würde eher den Aufzug nehmen, um ein Stockwerk zu fahren?",
    "Wer würde eher bei \"Wer wird Millionär\" bei 500 Euro rausfliegen?",
    "Wer würde eher sich mit dem Uber-Fahrer anfreunden?",
    "Wer würde eher den Fernseher mit einer Fernbedienung vom Nachbarn steuern?",
    "Wer würde eher auf einer Party die Polizei rufen?",
    "Wer würde eher den Hund eines Fremden mit nach Hause nehmen?",
    "Wer würde eher den ganzen Tag über Wetter reden?",
    "Wer würde eher für ein Foto auf einen Berg klettern?",
    "Wer würde eher das Handy in einem Vulkan verlieren?",
    "Wer würde eher Vegan werden und es nach einer Woche vergessen?",
    "Wer würde eher im Casino alles setzen?",
    "Wer würde eher in einer Bar eine Runde für alle bestellen und dann nicht zahlen können?",
    "Wer würde eher eine Stunde vor einem Termin schon da sein?",
    "Wer würde eher mit Vollgas in einen Verkehrsstau fahren, weil Navi aus?",
    "Wer würde eher ein Praktikum bei der NASA bekommen?",
    "Wer würde eher den Schlüssel in der Tür von außen stecken lassen?",
    "Wer würde eher mit einem Alien Freundschaft schließen?",
    "Wer würde eher den Papst um ein Selfie bitten?",
    "Wer würde eher eine Petition für ein zweites Frühstück starten?",
    "Wer würde eher in einem Fahrstuhl stecken bleiben und singen?",
    "Wer würde eher ein Auto kaufen, ohne Führerschein zu haben?",
    "Wer würde eher beim Schwarzfahren einen Fahrschein finden?",
    "Wer würde eher mitten in einer Rede vergessen, worum es geht?",
    "Wer würde eher den Weihnachtsmann auf einer Party spielen?",
    "Wer würde eher beim Camping das Zelt falschrum aufbauen?",
    "Wer würde eher aus einem Restaurant ohne zu zahlen gehen, ohne es zu merken?",
    "Wer würde eher mit dem Haustier im Restaurant reden?",
    "Wer würde eher sich als Lehrer verkleiden, um in die Schule zu kommen?",
    "Wer würde eher am Bahnsteig in den falschen Zug steigen?",
    "Wer würde eher eine Fernbeziehung mit jemandem aus Australien führen?",
    "Wer würde eher einen ganzen Tag lang lächeln, weil das Handy kaputt ist?",
    "Wer würde eher mitten in der Nacht Sport machen?",
    "Wer würde eher bei einem Bewerbungsgespräch einschlafen?",
    "Wer würde eher den Nachbarn wegen Musik anzeigen?",
    "Wer würde eher im Fitnessstudio mit den Spiegeln flirten?",
    "Wer würde eher beim Angeln ins Wasser fallen?",
    "Wer würde eher in der Schlange vom Kino den falschen Film kaufen?",
    "Wer würde eher mit seinen Eltern Urlaub in einem Bett-Hostel machen?",
    "Wer würde eher sich mit einem Automaten streiten?",
    "Wer würde eher einen Elefanten als Haustier wollen?",
    "Wer würde eher in der Fußgängerzone ein Straßenkonzert geben?",
    "Wer würde eher den Titel \"Miss Party\" gewinnen?",
    "Wer würde eher im Restaurant nach dem Rezept fragen?",
    "Wer würde eher mit einem Roboter reden, als sei er ein Mensch?",
    "Wer würde eher bei einem Vorstellungsgespräch das Gehalt zuerst nennen?",
    "Wer würde eher seine Playlist auf einer Beerdigung laufen lassen?",
    "Wer würde eher den Kellner umarmen?",
    "Wer würde eher das Auto im Halteverbot parken und Glück haben?",
    "Wer würde eher in einem Meeting ein Nickerchen halten?",
    "Wer würde eher den Nachbarn zur Silvesterparty einladen?",
    "Wer würde eher eine Kochshow gewinnen?",
    "Wer würde eher zu spät zur eigenen Hochzeit kommen?",
    "Wer würde eher mit den Schwiegereltern in den Urlaub fahren?",
    "Wer würde eher am Bahnhof jemanden falsch abholen?",
    "Wer würde eher nach einem Streit als Erstes nachgeben?",
    "Wer würde eher beim Grillen die Wurst vergessen?",
    "Wer würde eher den Sommer über nur Sandalen tragen?",
    "Wer würde eher zum Yoga gehen und nach fünf Minuten wieder gehen?",
    "Wer würde eher mit einem Einhorn tanzen?",
    "Wer würde eher Klavier lernen und nach einer Woche aufgeben?",
    "Wer würde eher eine Talkshow moderieren?",
    "Wer würde eher aus Versehen ein Auto klauen, weil es ähnlich aussah?",
    "Wer würde eher den Hausschlüssel als Werkzeug benutzen?",
    "Wer würde eher nach Mitternacht Backen anfangen?",
    "Wer würde eher beim Zelten nachts panisch werden?",
    "Wer würde eher sich als Statist in einem Film schmuggeln?",
    "Wer würde eher ein Tinder-Profil für den Hund anlegen?",
    "Wer würde eher am Wochenende arbeiten, ohne es zu müssen?",
    "Wer würde eher das Auto beim Waschen kaputt machen?",
    "Wer würde eher das Wort \"Deadline\" ignorieren?",
    "Wer würde eher den Teekocher als Wecker nutzen?",
    "Wer würde eher ein Kind beim Spielen im Park verlieren?",
    "Wer würde eher in einem Fitnesskurs falsch mitmachen?",
    "Wer würde eher auf einer Hochzeit ein Gedicht vortragen?",
    "Wer würde eher ein Auto in den Pool fahren?",
    "Wer würde eher den Bartender heiraten?",
    "Wer würde eher sich beim Sonnen wie ein Hummer verbrennen?",
    "Wer würde eher den Hausarzt wegen einer Erkältung anrufen?",
    "Wer würde eher mit dem Fahrrad in ein Kaufhaus fahren?",
    "Wer würde eher den Fernseher beim Spielen schmeißen?",
    "Wer würde eher bei einem Spiel schummeln?",
    "Wer würde eher Aufräumen, um Aufgaben zu vermeiden?",
    "Wer würde eher den Wecker verlegen und trotzdem aufwachen?",
    "Wer würde eher einen Song im Radio mitgrölen?",
    "Wer würde eher sich im Kino mit Fremden unterhalten?",
    "Wer würde eher mit dem Auto in den Graben fahren?",
    "Wer würde eher die Fähre verpassen und schwimmen?",
    "Wer würde eher bei Regen ohne Jacke rausgehen?",
    "Wer würde eher das Fahrrad im Zug vergessen?",
    "Wer würde eher mit einem Fremden Freundschaftsarmbänder tauschen?",
    "Wer würde eher ein Alkoholverbot auf einer Party verhängen?",
    "Wer würde eher das Auto beim Tanken nicht mehr finden?",
    "Wer würde eher den Kellner um ein Autogramm bitten?",
    "Wer würde eher beim Skifahren ohne Übung die schwarze Piste nehmen?",
    "Wer würde eher das ganze Wochenende in der Bibliothek verbringen?",
    "Wer würde eher den Nachbarn aus Versehen kündigen?",
    "Wer würde eher beim Bowling mit der Kugel wegrutschen?",
    "Wer würde eher ein Puzzle nie fertig machen?",
    "Wer würde eher im Restaurant das Trinkgeld vergessen?",
    "Wer würde eher in einer Gruppe als Einziges Wasser bestellen?",
    "Wer würde eher einen Hund auf einer Party klauen?",
    "Wer würde eher ein Lied im Radio wünschen?",
    "Wer würde eher das Datum der Hochzeit vergessen?",
    "Wer würde eher mit einer Schaufel im Stau stehen?",
    "Wer würde eher sich im Fitnessstudio verlaufen?",
    "Wer würde eher das Gepäck am Flughafen vertauschen?",
    "Wer würde eher auf einem Pferd einschlafen?",
    "Wer würde eher Windeln kaufen, ohne Kinder zu haben?",
    "Wer würde eher das Lieblingsessen einem Fremden abgeben?",
    "Wer würde eher den falschen Zug nehmen und trotzdem ankommen?",
    "Wer würde eher ein Wochenende ohne Internet freiwillig durchziehen?",
    "Wer würde eher die Bedienungsanleitung lesen, bevor etwas kaputt ist?",
    "Wer würde eher das Auto mit leerem Tank liegen lassen?",
    "Wer würde eher bei einem Konzert auf die Bühne klettern?",
    "Wer würde eher seinen Kaffee mit fünf Zuckern trinken?",
    "Wer würde eher eine Lebensgeschichte an der Supermarktkasse erzählen?",
    "Wer würde eher den Sonnenuntergang verschlafen, weil ein Nickerchen zu lang wurde?",
    "Wer würde eher sich mit einem Straßenkünstler anfreunden?",
    "Wer würde eher ein Gruppenfoto mit geschlossenen Augen ruinieren?",
    "Wer würde eher mit Socken in Sandalen in den Urlaub fahren?",
    "Wer würde eher im Supermarkt an der Wursttheke ein Stück Wurst für die Kinder verlangen?",
    "Wer würde eher mit dem Hund im Restaurant eine Vorspeise teilen?",
    "Wer würde eher den falschen Geburtstag im Kalender eintragen?",
    "Wer würde eher bei einem Spieleabend die Regeln nachschlagen und trotzdem verlieren?",
    "Wer würde eher das Handy auf lautlos stellen und dann nie wieder finden?",
    "Wer würde eher im Winter mit kurzer Hose rausgehen?",
    "Wer würde eher auf einer Hochzeit den Brautstrauß fangen?",
    "Wer würde eher ein Wochenende lang nur Pizza essen?",
    "Wer würde eher eine Kaffeetasse im Büro adoptieren?",
    "Wer würde eher ein Auto beim Wenden auf der Autobahn stehen lassen?",
    "Wer würde eher einen Berg bei Nacht besteigen?",
    "Wer würde eher in einer Bar den Barkeeper heiraten wollen?",
    "Wer würde eher einen Kuchen mit Salz statt Zucker backen?",
    "Wer würde eher mit dem Fahrrad zum Club fahren und zu Fuß zurück?",
    "Wer würde eher den Weihnachtsmarkt schon im Oktober vermissen?",
    "Wer würde eher sich im eigenen Haus verlaufen?",
    "Wer würde eher das Lieblingsshirt heimlich waschen und einlaufen lassen?",
    "Wer würde eher den Kinobesuch wegen Popcorn-Preisen absagen?",
    "Wer würde eher mit Vollgas in die Falle \"gratis Probemonat\" tappen?",
  ],

  // Schätzfragen – am weitesten daneben trinkt 3, zweitweiteste 1
  schaetz: [
    { q: "Wie viele Knochen hat ein erwachsener Mensch?", a: 206, unit: "" },
    { q: "Wie hoch ist der Eiffelturm in Metern (mit Antenne)?", a: 330, unit: "m" },
    { q: "Wie viele Länder gibt es in Afrika?", a: 54, unit: "" },
    { q: "Wie viele Tasten hat ein Klavier?", a: 88, unit: "" },
    { q: "Wie lang ist der Rhein in Kilometern?", a: 1233, unit: "km" },
    { q: "Wie viele Zähne hat ein Erwachsener mit Weisheitszähnen?", a: 32, unit: "" },
    { q: "Wie viele Einwohner hat Berlin ungefähr (in Millionen)?", a: 3.9, unit: "Mio" },
    { q: "Wie viele Sekunden hat ein Tag?", a: 86400, unit: "s" },
    { q: "Wie viel wiegt ein Elefantenbulle ungefähr (in Kilogramm)?", a: 6000, unit: "kg" },
    { q: "Wie viele Bundesländer hat Deutschland?", a: 16, unit: "" },
    { q: "Wie viel Prozent der Erdoberfläche sind Wasser?", a: 71, unit: "%" },
    { q: "Wie hoch ist der Mount Everest in Metern?", a: 8849, unit: "m" },
    { q: "Wie viele Spieler stehen bei einem Fußballspiel auf dem Platz?", a: 22, unit: "" },
    { q: "Wie viele Herzschläge hat ein Mensch etwa pro Tag?", a: 100000, unit: "" },
    { q: "Wie viele Grad hat ein Kreis?", a: 360, unit: "°" },
    { q: "Wie viele Kalorien hat ein Liter Bier ungefähr?", a: 430, unit: "kcal" },
    { q: "Wie viele Kilometer sind es Luftlinie von Berlin nach München?", a: 504, unit: "km" },
    { q: "Wie viel Prozent Alkohol hat ein klassischer Wodka?", a: 40, unit: "%" },
    { q: "Wie viele Sterne hat die Flagge der EU?", a: 12, unit: "" },
    { q: "Wie viele Tage hat ein Schaltjahr?", a: 366, unit: "" },
    { q: "In welchem Jahr fiel die Berliner Mauer?", a: 1989, unit: "" },
    { q: "Wie viele Karten hat ein Skatblatt?", a: 32, unit: "" },
    { q: "Wie viele Mitgliedsstaaten hat die EU?", a: 27, unit: "" },
    { q: "Wie viele Minuten hat ein Tag?", a: 1440, unit: "min" },
    { q: "Wie lang ist die Chinesische Mauer ungefähr in Kilometern?", a: 21000, unit: "km" },
    { q: "Wie viele Einwohner hat Deutschland ungefähr (in Millionen)?", a: 84, unit: "Mio" },
    { q: "Wie viele Knochen hat ein Neugeborenes ungefähr?", a: 300, unit: "" },
    { q: "Wie viele Liter Blut hat ein erwachsener Mensch ungefähr?", a: 5, unit: "l" },
    { q: "Wie hoch ist der Kölner Dom in Metern?", a: 157, unit: "m" },
    { q: "Wie viel Grad Celsius hat der Körper normalerweise?", a: 37, unit: "°C" },
    { q: "Wie viele Jahre hat ein Jahrhundert?", a: 100, unit: "" },
    { q: "Wie viele Zähne hat ein Hai ungefähr im Laufe seines Lebens?", a: 30000, unit: "" },
    { q: "Wie viele Sitze hat der Bundestag laut Gesetz seit 2025?", a: 630, unit: "" },
    { q: "Wie viele Meter hat eine Seemeile?", a: 1852, unit: "m" },
    { q: "Wie hoch ist die Schallgeschwindigkeit in km/h ungefähr?", a: 1235, unit: "km/h" },
    { q: "Wie viele Tage dauert eine Schwangerschaft ungefähr?", a: 280, unit: "" },
    { q: "Wie viele Knochen hat eine Hand?", a: 27, unit: "" },
    { q: "Wie viele Einwohner hat die Erde ungefähr (in Milliarden)?", a: 8.2, unit: "Mrd" },
    { q: "Wie viele Kilometer ist der Mond von der Erde entfernt (Durchschnitt)?", a: 384400, unit: "km" },
    { q: "Wie viele Muskeln hat der Mensch ungefähr?", a: 650, unit: "" },
    { q: "Wie hoch ist der Berliner Fernsehturm in Metern?", a: 368, unit: "m" },
    { q: "Wie viele Jahre hat ein Hund im Schnitt gelebt (mittlere Rasse)?", a: 12, unit: "" },
    { q: "Wie viele Sekunden hat eine Stunde?", a: 3600, unit: "s" },
    { q: "Wie viele Prozent des Gehirns bestehen aus Wasser?", a: 75, unit: "%" },
    { q: "Wie lange dauert es ungefähr, bis Sonnenlicht die Erde erreicht (in Minuten)?", a: 8, unit: "min" },
    { q: "Wie viele Rippen hat ein Mensch?", a: 24, unit: "" },
    { q: "Wie viele Sprachen werden weltweit ungefähr gesprochen?", a: 7000, unit: "" },
    { q: "Wie viele Kilometer lang ist die Donau?", a: 2857, unit: "km" },
    { q: "Wie viel Prozent Alkohol hat ein durchschnittliches Pils?", a: 4.9, unit: "%" },
    { q: "Wie viele Einwohner hat Hamburg ungefähr (in Millionen)?", a: 1.9, unit: "Mio" },
    { q: "Wie schwer ist ein Liter Wasser in Gramm?", a: 1000, unit: "g" },
    { q: "Wie viele Meter hat ein Fußballfeld in der Länge (Standard)?", a: 105, unit: "m" },
    { q: "Wie viele Jahre alt wurde Queen Elizabeth II.?", a: 96, unit: "" },
    { q: "Wie viele Tasten hat eine Standard-PC-Tastatur ungefähr?", a: 104, unit: "" },
    { q: "Wie viele Stunden schläft eine Katze pro Tag ungefähr?", a: 14, unit: "h" },
    { q: "Wie viele Sitze hat ein Airbus A380 in Standard-Konfiguration ungefähr?", a: 525, unit: "" },
    { q: "Wie hoch ist der Burj Khalifa in Metern?", a: 828, unit: "m" },
    { q: "Wie viele Länder gibt es auf der Welt (UN-Mitglieder)?", a: 193, unit: "" },
    { q: "Wie viele Bit hat eine IPv4-Adresse?", a: 32, unit: "" },
    { q: "Wie viel Prozent der Deutschen tragen eine Brille ungefähr?", a: 64, unit: "%" },
    { q: "Wie viele Kilometer lang ist die deutsche Autobahn ungefähr?", a: 13200, unit: "km" },
    { q: "Wie viele Millionen Menschen sprechen Deutsch als Muttersprache ungefähr?", a: 95, unit: "Mio" },
    { q: "Wie viel kostet ein Liter Super E10 in Deutschland ungefähr (in Cent)?", a: 175, unit: "ct" },
    { q: "Wie viele Kilometer läuft man bei einem Halbmarathon?", a: 21.1, unit: "km" },
    { q: "Wie viele Oscars hat der Film Titanic gewonnen?", a: 11, unit: "" },
    { q: "Wie viele Tore hat Miroslav Klose bei Weltmeisterschaften erzielt?", a: 16, unit: "" },
    { q: "Wie viele Minuten dauert ein Eishockeyspiel regulär (reine Spielzeit)?", a: 60, unit: "min" },
    { q: "Wie viele Punkte hat ein Basketball-Dreier-Wurf?", a: 3, unit: "" },
    { q: "Wie viel wiegt ein Blauwal ungefähr in Tonnen?", a: 150, unit: "t" },
    { q: "Wie viele Meter ist der tiefste Punkt der Ozeane tief (Marianengraben)?", a: 10935, unit: "m" },
    { q: "Wie viele Tage hat ein Jahr auf dem Mars ungefähr (Erdtage)?", a: 687, unit: "" },
    { q: "Wie viel Grad Celsius ist der Siedepunkt von Wasser auf Meereshöhe?", a: 100, unit: "°C" },
    { q: "Wie viele Farben hat ein Regenbogen klassischerweise?", a: 7, unit: "" },
    { q: "Wie viele Ecken hat ein Zwölfeck?", a: 12, unit: "" },
    { q: "Wie hoch ist der Bierkonsum in Deutschland pro Kopf und Jahr ungefähr (Liter)?", a: 88, unit: "l" },
    { q: "Wie viele Kalorien hat ein Big Mac ungefähr?", a: 500, unit: "kcal" },
    { q: "Wie viele Gramm Zucker sind in einer Dose Cola (330 ml)?", a: 35, unit: "g" },
    { q: "Wie viel wiegt ein Fußball ungefähr in Gramm?", a: 430, unit: "g" },
    { q: "Wie viele Meter ist eine olympische Schwimmbahn lang?", a: 50, unit: "m" },
    { q: "Wie viele Ringe hat das Olympia-Logo?", a: 5, unit: "" },
    { q: "Wie viele Kilometer hat eine Formel-1-Renndistanz ungefähr?", a: 305, unit: "km" },
    { q: "Wie viele Seiten hat ein Würfel?", a: 6, unit: "" },
    { q: "Wie viele Sekunden hat der Weltrekord im 100-Meter-Lauf der Männer?", a: 9.58, unit: "s" },
    { q: "Wie viele Sitzplätze hat der Signal Iduna Park in Dortmund ungefähr?", a: 81365, unit: "" },
    { q: "Wie viele Prozent Kakao hat Zartbitterschokolade mindestens?", a: 50, unit: "%" },
    { q: "Wie hoch ist die Zugspitze in Metern?", a: 2962, unit: "m" },
    { q: "Wie viele Nullen hat eine Milliarde?", a: 9, unit: "" },
    { q: "Wie viele Einwohner hat Pforzheim ungefähr?", a: 127000, unit: "" },
    { q: "Wie viele Kilometer ist es von Pforzheim nach Stuttgart (Auto)?", a: 50, unit: "km" },
    { q: "Wie viele Prozent der Menschen sind Linkshänder ungefähr?", a: 10, unit: "%" },
    { q: "Wie viele Jahre alt ist die Gletschermumie Ötzi ungefähr?", a: 5300, unit: "" },
    { q: "Wie viele Tage hat der Februar in einem Schaltjahr?", a: 29, unit: "" },
    { q: "Wie viele Spielfelder hat ein Schachbrett?", a: 64, unit: "" },
    { q: "Wie viele Streichhölzer sind in einer Standardpackung ungefähr?", a: 38, unit: "" },
    { q: "Wie viele Kilometer fährt ein Auto in Deutschland durchschnittlich pro Jahr?", a: 12000, unit: "km" },
    { q: "Wie viele Mitglieder hatte die Boyband One Direction ursprünglich?", a: 5, unit: "" },
    { q: "Wie hoch ist die Freiheitsstatue in Metern (ohne Sockel)?", a: 46, unit: "m" },
    { q: "Wie viele Buchstaben hat das deutsche Alphabet (ohne Umlaute und ß)?", a: 26, unit: "" },
    { q: "Wie viele Liter fasst ein Standard-Bierfass (Keg) in der Gastronomie?", a: 50, unit: "l" },
    { q: "Wie viele Milliliter hat ein Maßkrug?", a: 1000, unit: "ml" },
  ],

  // Wahrheit oder Pflicht – zufällige Person, kneifen kostet 3
  wahrheit: [
    "Was war dein peinlichster Moment in den letzten zwölf Monaten?",
    "Wen in dieser Runde würdest du als Erstes auf eine einsame Insel mitnehmen?",
    "Welche Lüge erzählst du am häufigsten?",
    "Was war das Kindischste, das du diese Woche gemacht hast?",
    "Welchen Song hörst du heimlich gerne, obwohl er dir peinlich ist?",
    "Was ist der seltsamste Ort, an dem du eingeschlafen bist?",
    "Wen aus der Runde hast du schon mal auf stumm geschaltet?",
    "Was ist das Teuerste, das du je kaputt gemacht hast?",
    "Welche Angewohnheit von dir nervt deine Freunde am meisten?",
    "Was war dein schlimmster Kater und wie kam es dazu?",
    "Was hast du als Letztes bei Google gesucht?",
    "Welche Ausrede hast du benutzt, um eine Einladung abzusagen?",
    "Was ist dein unbeliebtestes Essen, das du trotzdem aus Höflichkeit gegessen hast?",
    "Wem würdest du am liebsten mal so richtig die Meinung sagen?",
    "Was ist dein größter Guilty-Pleasure-Film?",
    "Was war das letzte Gerücht, das du weitererzählt hast?",
    "Wann hast du das letzte Mal gelogen und warum?",
    "Was ist deine schlechteste Angewohnheit im Bad?",
    "Welchen Promi findest du heimlich attraktiv, den niemand verstehen würde?",
    "Was hast du in deiner Kindheit geklaut?",
    "Was ist das Peinlichste in deinem Suchverlauf?",
    "Wer hier war dir beim ersten Treffen unsympathisch?",
    "Wie viele Leute hast du geküsst?",
    "Was ist deine schlimmste Essgewohnheit?",
    "Welches Geheimnis hast du deinen Eltern nie erzählt?",
    "Welche Serie hast du abgebrochen, weil sie zu emotional war?",
    "Bei welchem Film hast du zuletzt geweint?",
    "Was war dein schlimmstes Date?",
    "Welchen Namen wolltest du als Kind haben?",
    "Was war dein erstes Passwort?",
    "Wann hast du das letzte Mal die Bettwäsche gewechselt?",
    "Was war deine schlechteste Schulnote?",
    "Was hast du schon mal aus dem Hotel mitgenommen?",
    "Wen hier würdest du im Zweifel als Erstes anlügen?",
    "Wie oft schaust du pro Tag aufs Handy?",
    "Was ist das Verrückteste, das du für Liebe getan hast?",
    "Was war die längste Zeit ohne Dusche?",
    "Welches Kleidungsstück trägst du zu oft?",
    "Was war deine peinlichste Frisur?",
    "Welches Talent hast du, das niemand kennt?",
    "Was ist dein größter Alkohol-Fehler?",
    "Welche App auf deinem Handy ist dir peinlich?",
    "Hast du schon mal einen Freund bei einem Partner schlechtgeredet?",
    "Was war das Letzte, worüber du richtig gestritten hast?",
    "Welche Angewohnheit deines Partners oder Ex hat dich am meisten genervt?",
    "Was war der schlimmste Job, den du hattest?",
    "Welches Geschenk hast du gehasst und trotzdem \"Danke\" gesagt?",
    "Wo hast du dich schon mal absichtlich verlaufen?",
    "Welchen Fehler machst du immer wieder?",
    "Was ist deine schlechteste Angewohnheit beim Autofahren?",
    "Wann hast du zuletzt jemanden geghostet?",
    "Wer hier hat den besten Style?",
    "Wem in der Runde vertraust du am wenigsten mit einem Geheimnis?",
    "Wann hast du das letzte Mal so getan, als wärst du beschäftigt?",
    "Was ist das Schrägste, das in deinem Kühlschrank ist?",
    "Welches Foto von dir würdest du nie posten?",
    "Was ist die größte Lüge, die du einem Lehrer erzählt hast?",
    "Welchen Spitznamen hattest du in der Schule?",
    "Was ist das Erste, was dir bei einem Menschen auffällt?",
    "Wie oft hast du dieses Jahr Sport gemacht, ehrlich?",
    "Was war das schlechteste Essen, das du je gekocht hast?",
    "Welchen deiner Freunde hast du schon mal verkuppelt?",
    "Welches Tier beschreibt dich betrunken am besten?",
    "Was war das Peinlichste, das dir beim Sport passiert ist?",
    "Wie viele ungelesene Mails hast du?",
    "Was würdest du tun, wenn du unsichtbar wärst?",
    "Bei wem in der Runde würdest du im Notfall wohnen?",
    "Welche Sache hast du jahrelang falsch ausgesprochen?",
    "Was ist dein Lieblingsschimpfwort?",
    "Welche schlechte Entscheidung hast du zweimal getroffen?",
    "Was war das Letzte, das du im Internet gekauft und bereut hast?",
    "Was war dein schlimmster Urlaubsmoment?",
    "Wie viele Stunden hast du diese Woche am Handy verbracht?",
    "Was ist dein Nummer-eins-Ausrede beim Absagen?",
    "Wann hast du zuletzt einen Kinderfilm geschaut?",
    "Welchen Tanz kannst du wirklich?",
    "Hast du je einen Freund gebeten, zu lügen?",
    "Was ist das Kindischste, das du noch besitzt?",
    "Welche Regel brichst du regelmäßig?",
    "Wem hier würdest du nie dein Handy geben?",
    "Was ist die längste Zeit, die du wach warst?",
    "Welchen Beruf wolltest du als Kind haben?",
    "Was war die schlechteste Idee einer Freundesgruppe, bei der du mitgemacht hast?",
    "Was hast du bei einem Nachbarn schon mal beobachtet?",
    "Was war dein absurdester Kaufrausch?",
    "Wann hast du das letzte Mal jemandem heimlich das Essen weggegessen?",
    "Welchen Film hast du mehr als fünfmal gesehen?",
    "Was ist dein Lieblingsplatz zum Denken?",
    "Wann warst du das letzte Mal in der Kirche?",
    "Welche Sportart würdest du niemals ausprobieren?",
    "Wie viele Stunden schläfst du wirklich?",
    "Was ist das Schlimmste, das du zu einem Kellner gesagt hast?",
    "Welches Getränk hast du nie wieder angerührt?",
    "Welchen Vorsatz hast du dieses Jahr am schnellsten gebrochen?",
    "Was war die schlechteste Bewertung, die du je bekommen hast?",
    "Hast du schon mal eine Party aus Neid geschwänzt?",
    "Wen hier findest du am lustigsten?",
    "Was ist das Nervigste an deinem besten Freund?",
    "Was war die schlimmste Frisur, die du jemandem verpasst hast?",
    "Was war das erste Konzert deines Lebens?",
  ],
  pflicht: [
    "Sprich bis zur nächsten Runde nur in Reimen.",
    "Lass dir vom Spieler links neben dir eine neue Frisur machen.",
    "Zeig der Runde das letzte Foto in deiner Galerie.",
    "Mach 15 Kniebeugen, während du die Nationalhymne summst.",
    "Ruf einen Kontakt an und sing \"Happy Birthday\", egal ob er Geburtstag hat.",
    "Trage bis zum Ende des Spiels einen Gegenstand als Hut.",
    "Sprich zwei Runden lang mit dem Akzent deiner Wahl.",
    "Imitiere einen Mitspieler, bis die Runde ihn errät.",
    "Poste eine Story mit deinem schlechtesten Gesichtsausdruck.",
    "Lass dir die Augen verbinden und errate, was dir ins Glas geschüttet wurde.",
    "Tanze 30 Sekunden ohne Musik.",
    "Mach ein Kompliment an jede Person in der Runde – ohne dich zu wiederholen.",
    "Sprich bis zur nächsten Runde in der dritten Person über dich.",
    "Schick deiner letzten WhatsApp-Kontaktperson einen Gute-Nacht-Gruß mit Herz.",
    "Erzähl einen Witz. Lacht keiner, trinkst du 2.",
    "Mach eine Minute lang Planke.",
    "Sing den Refrain deines Lieblingslieds so laut du kannst.",
    "Lass die Runde deinen nächsten Instagram-Post bestimmen.",
    "Zeichne mit geschlossenen Augen einen Mitspieler.",
    "Sprich bis zur nächsten Runde nur in Fragen.",
    "Trink dein Getränk mit der falschen Hand bis zum Spielende.",
    "Schreibe einer zufälligen Person \"Ich muss dir was sagen\" und warte.",
    "Mach zehn Liegestütze.",
    "Erzähle eine peinliche Geschichte aus deiner Schulzeit.",
    "Sprich zwei Minuten lang wie ein Nachrichtensprecher.",
    "Lass jemanden dein Handy 30 Sekunden benutzen.",
    "Gehe wie ein Roboter zum Kühlschrank und zurück.",
    "Tausche ein Kleidungsstück mit dem Spieler rechts von dir.",
    "Mach eine Runde lang alles nach, was der Roundmaster macht.",
    "Erkläre die Regeln von Schach in 30 Sekunden.",
    "Sag die nächsten drei Sätze rückwärts.",
    "Mach ein Selfie mit allen und schicke es der Mutter eines Mitspielers.",
    "Sing das Alphabet als Opernarie.",
    "Rede eine Runde lang wie ein Pirat.",
    "Flüstere bis zur nächsten Runde.",
    "Lass dir von der Runde einen neuen Spitznamen geben, der ab jetzt gilt.",
    "Mach den Moonwalk durchs Zimmer.",
    "Erzähle eine Gute-Nacht-Geschichte über deinen Sitznachbarn.",
    "Lass dir von einem Mitspieler mit Stift ein Tattoo malen.",
    "Stell dir eine Minute lang vor, du bist ein Baum, und bleib so.",
    "Mach das Geräusch von drei Tieren, die Runde rät.",
    "Bestell laut eine imaginäre Pizza mit den verrücktesten Belägen.",
    "Halte eine Motivationsrede für den Mitspieler, der gerade am meisten getrunken hat.",
    "Zeig deinen besten Tanzmove zweimal hintereinander.",
    "Erzähl den Plot deines Lieblingsfilms in einem Satz.",
    "Lass die Runde drei Fragen zu deinem Handy stellen und antworte ehrlich.",
    "Mach mit einem Mitspieler einen Handschlag mit fünf Schritten und wiederhole ihn.",
    "Sag zu jedem Mitspieler ein Wort, das dir beim Anschauen als Erstes einfällt.",
    "Sprich bis zur nächsten Runde nur mit Emojis (also beschreibe sie laut).",
    "Mach einen Purzelbaum oder trink 2.",
    "Lauf zum nächsten Fenster und ruf \"Ich liebe Trinkspiele!\"",
    "Zeig deine Wallpaper-Historie.",
    "Sprich für den Rest der Runde in Reimen mit dem Namen des Sitznachbarn.",
    "Stell dich auf ein Bein, bis die nächste Frage kommt.",
    "Lass dich von der Runde zu einer Statue formen und bleib 30 Sekunden so.",
    "Schreib ein Vierzeiler-Gedicht über Bier und trag es vor.",
    "Mach ein Foto von deinem Kühlschrankinhalt und zeig es.",
    "Sing dein Lieblingslied als Rap.",
    "Rede bis zur nächsten Runde wie ein Fußballkommentator.",
    "Erzähl ein Geheimnis über dich, das die Runde nicht kennt.",
    "Mach ein Kompliment an dich selbst im Spiegel, laut.",
    "Balanciere ein Glas auf dem Kopf für zehn Sekunden.",
    "Verliere absichtlich ein Schere-Stein-Papier gegen den Sitznachbarn – dreimal.",
    "Mach ein Tier nach, bis jemand errät, welches.",
    "Imitiere den Roundmaster eine Minute lang.",
    "Erkläre der Runde, wie man ein Kind macht – aber nur mit Kochbegriffen.",
    "Beschreibe deine Woche wie einen Wetterbericht.",
    "Lass die Runde entscheiden, welchen Song du jetzt singst.",
    "Schreib \"Ich vermisse dich\" an deinen letzten Kontakt und zeig die Antwort.",
    "Trink ein Glas Wasser in einem Zug.",
    "Lauf um das Haus oder die Wohnung, so schnell du kannst.",
    "Mach ein Interview mit dem Getränk in deiner Hand.",
    "Sprich eine Runde lang, als wärst du sehr müde.",
    "Sag drei Dinge, die du an dir selbst magst.",
    "Mach eine Gruppenumarmung mit allen, die wollen.",
    "Erfinde einen neuen Trinkspruch und alle stoßen damit an.",
    "Zeig den Text deiner letzten drei Nachrichten.",
    "Sprich, als wärst du ein Kleinkind, bis zur nächsten Runde.",
    "Mach deine beste Elvis-Imitation.",
    "Vergib in der Runde einen Preis für die beste Frisur und halte die Laudatio.",
  ],

  // Entweder oder – Minderheit trinkt 1
  oder: [
    ["Bier", "Wein"],
    ["Sommer", "Winter"],
    ["Netflix-Abend", "Clubnacht"],
    ["Pizza", "Burger"],
    ["Strand", "Berge"],
    ["Frühaufsteher", "Nachteule"],
    ["Hund", "Katze"],
    ["Fliegen können", "Unsichtbar sein"],
    ["Nie wieder Handy", "Nie wieder Auto"],
    ["Kaffee", "Tee"],
    ["Süß", "Salzig"],
    ["Zug", "Flugzeug"],
    ["Zehn Jahre in die Zukunft", "Zehn Jahre in die Vergangenheit"],
    ["Immer laut reden", "Immer flüstern"],
    ["Sushi", "Döner"],
    ["Gaming", "Sport"],
    ["Lieber immer zu früh", "Lieber immer zu spät"],
    ["Kochen", "Bestellen"],
    ["Meer ohne Netz", "Stadt ohne Schlaf"],
    ["Cocktail", "Shot"],
    ["Android", "iPhone"],
    ["Wohnung in der Stadt", "Haus auf dem Land"],
    ["Regen", "Hitze"],
    ["Buch", "Film"],
    ["Freibad", "Hallenbad"],
    ["Fußball", "Basketball"],
    ["Duschen", "Baden"],
    ["Spotify", "Radio"],
    ["Frühstück", "Abendessen"],
    ["Gedankenlesen", "In die Zukunft sehen"],
    ["Berühmt sein", "Reich sein"],
    ["Schokolade", "Chips"],
    ["Auto", "Fahrrad"],
    ["Currywurst", "Pommes"],
    ["Konzert", "Festival"],
    ["Netflix", "YouTube"],
    ["Kino", "Couch"],
    ["Pasta", "Reis"],
    ["Skifahren", "Surfen"],
    ["Nachts schwimmen", "Nachts wandern"],
    ["Wodka", "Tequila"],
    ["Camping", "Hotel"],
    ["Hip-Hop", "Rock"],
    ["Ein Jahr kein Zucker", "Ein Jahr kein Alkohol"],
    ["Mit Delfinen schwimmen", "Mit Löwen kuscheln"],
    ["Für immer 25", "Für immer 50"],
    ["Nie wieder Musik", "Nie wieder Serien"],
    ["Playstation", "PC"],
    ["Morgens Sport", "Abends Sport"],
    ["Rooftop-Bar", "Kneipe"],
    ["Wohnmobil", "Zelt"],
    ["Deutsch-Rap", "Schlager"],
    ["Oktoberfest", "Karneval"],
    ["Schnee", "Sonne"],
    ["Gute Freunde", "Große Familie"],
    ["Frisches Brot", "Warmer Kuchen"],
    ["Kaltes Bier", "Warmer Glühwein"],
    ["Klavier spielen können", "Zeichnen können"],
    ["Hausparty", "Barhopping"],
    ["Motorrad", "Cabrio"],
    ["Zwei Wochen Thailand", "Zwei Wochen Norwegen"],
    ["Gin Tonic", "Aperol Spritz"],
    ["Sandwich", "Wrap"],
    ["Immer Jogginghose", "Immer Anzug"],
    ["Zug durch Europa", "Roadtrip USA"],
    ["Karaoke", "Darts"],
    ["Cheesecake", "Tiramisu"],
    ["Eiskaffee", "Heiße Schokolade"],
    ["Umzug jedes Jahr", "Nie umziehen"],
    ["Fenster", "Gang"],
    ["Salsa", "Techno"],
    ["Steak", "Sushi"],
    ["Nie wieder Pizza", "Nie wieder Pasta"],
    ["Wecker um 5", "Wecker um 10"],
    ["Poolparty", "Strandparty"],
    ["Ein Haustier", "Kein Haustier"],
    ["Grillen", "Fondue"],
    ["Wochenende in Berlin", "Wochenende in München"],
    ["Leben ohne Internet", "Leben ohne Sonne"],
    ["Schokoladeneis", "Vanilleeis"],
    ["Fremdsprache lernen", "Instrument lernen"],
    ["Feuerwerk", "Lagerfeuer"],
    ["Kurze Haare", "Lange Haare"],
    ["Immer Schlaf", "Immer Party"],
    ["Wein am Kamin", "Bier am See"],
    ["Kreuzfahrt", "Backpacking"],
    ["Comedy", "Horror"],
    ["Superkraft Zeit anhalten", "Superkraft Teleportation"],
    ["Morgens duschen", "Abends duschen"],
    ["Baguette", "Brezel"],
    ["Frühling", "Herbst"],
    ["Sonnenbrille", "Cap"],
    ["Reggae", "Country"],
    ["Selbst kochen für zehn", "Eingeladen sein bei zehn"],
    ["Live-Konzert", "Theater"],
    ["Zocken bis vier", "Feiern bis vier"],
    ["Tanzen", "Singen"],
    ["Lakritz", "Gummibärchen"],
    ["Weltreise", "Traumhaus"],
    ["Cola", "Fanta"],
    ["Sekt", "Prosecco"],
    ["Süßer Wein", "Trockener Wein"],
    ["Ein Wunsch", "Drei Freunde"],
    ["Dauerregen", "Dauerwind"],
    ["Pizza mit Ananas", "Pizza ohne Käse"],
    ["Reisen in die Vergangenheit", "Reisen in die Zukunft"],
    ["Nur noch Nachrichten", "Nur noch Anrufe"],
    ["Bäcker", "Metzger"],
    ["Eigene Insel", "Eigenes Flugzeug"],
    ["Bergsee", "Ozean"],
    ["Kaffee mit Milch", "Kaffee schwarz"],
    ["Tortilla", "Naan"],
    ["Schwarz", "Weiß"],
    ["Sonntag", "Freitag"],
    ["Bier vom Fass", "Bier aus der Flasche"],
    ["Eigene Bar", "Eigenes Restaurant"],
    ["Weiße Weihnacht", "Warme Weihnacht"],
    ["Nie mehr Fleisch", "Nie mehr Käse"],
    ["Immer Brille", "Immer Kontaktlinsen"],
    ["Regenschirm", "Regenjacke"],
    ["Marmelade", "Nutella"],
    ["Bowling", "Minigolf"],
    ["Oldtimer", "Elektroauto"],
    ["Wohnzimmer-Party", "Küchen-Party"],
    ["Hängematte", "Liegestuhl"],
    ["Gedicht vortragen", "Lied singen"],
    ["Zocken auf Handy", "Zocken auf Konsole"],
    ["Butterbrezel", "Käsebrötchen"],
    ["Bahnfahrt 8 Stunden", "Autofahrt 8 Stunden"],
  ],

  // Trivia – 4 Antworten, wer falsch liegt trinkt 1
  trivia: [
    { q: "Welcher Planet ist der größte in unserem Sonnensystem?", o: ["Saturn", "Jupiter", "Neptun", "Uranus"], c: 1 },
    { q: "Wie viele Herzen hat ein Oktopus?", o: ["1", "2", "3", "4"], c: 2 },
    { q: "Welche Stadt ist die Hauptstadt von Australien?", o: ["Sydney", "Melbourne", "Canberra", "Perth"], c: 2 },
    { q: "Aus welchem Land stammt der Tequila?", o: ["Spanien", "Kuba", "Mexiko", "Brasilien"], c: 2 },
    { q: "Welches Element hat das chemische Symbol Au?", o: ["Silber", "Gold", "Aluminium", "Argon"], c: 1 },
    { q: "Wie viele Spieler hat eine Volleyball-Mannschaft auf dem Feld?", o: ["5", "6", "7", "8"], c: 1 },
    { q: "Welches Tier ist das schnellste Landtier?", o: ["Gepard", "Löwe", "Antilope", "Windhund"], c: 0 },
    { q: "In welchem Jahr war die erste Mondlandung?", o: ["1965", "1967", "1969", "1971"], c: 2 },
    { q: "Welcher Fluss gilt als der längste der Welt?", o: ["Amazonas", "Nil", "Jangtse", "Mississippi"], c: 1 },
    { q: "Wie viele Streifen hat die US-Flagge?", o: ["11", "13", "15", "50"], c: 1 },
    { q: "Welche Sprache hat die meisten Muttersprachler?", o: ["Englisch", "Spanisch", "Mandarin", "Hindi"], c: 2 },
    { q: "Was ist die Hauptzutat von Guacamole?", o: ["Gurke", "Avocado", "Erbse", "Spinat"], c: 1 },
    { q: "Welches Organ produziert Insulin?", o: ["Leber", "Niere", "Bauchspeicheldrüse", "Milz"], c: 2 },
    { q: "Wie heißt die Währung in Japan?", o: ["Won", "Yuan", "Yen", "Ringgit"], c: 2 },
    { q: "Welcher Ozean ist der größte?", o: ["Atlantik", "Indischer Ozean", "Arktischer Ozean", "Pazifik"], c: 3 },
    { q: "Wie viele Bit sind ein Byte?", o: ["4", "8", "16", "32"], c: 1 },
    { q: "Welches Getränk wird mit Wacholderbeeren aromatisiert?", o: ["Rum", "Gin", "Wodka", "Whisky"], c: 1 },
    { q: "Wie viele Saiten hat eine klassische Gitarre?", o: ["4", "5", "6", "7"], c: 2 },
    { q: "Welches Land hat die meisten Einwohner?", o: ["China", "Indien", "USA", "Indonesien"], c: 1 },
    { q: "Wie heißt der höchste Berg Deutschlands?", o: ["Watzmann", "Zugspitze", "Feldberg", "Brocken"], c: 1 },
    { q: "Welche Farbe entsteht aus Blau und Gelb?", o: ["Orange", "Lila", "Grün", "Braun"], c: 2 },
    { q: "Wie viele Minuten hat ein Fußballspiel regulär?", o: ["80", "90", "100", "120"], c: 1 },
    { q: "Welcher Vogel kann nicht fliegen?", o: ["Pinguin", "Papagei", "Taube", "Adler"], c: 0 },
    { q: "Was ist H2O?", o: ["Wasserstoffperoxid", "Wasser", "Kohlendioxid", "Ozon"], c: 1 },
    { q: "Aus welchem Land kommt die Pizza ursprünglich?", o: ["Griechenland", "Frankreich", "Italien", "Spanien"], c: 2 },
    { q: "Wie viele Zeitzonen hat Russland?", o: ["5", "7", "9", "11"], c: 3 },
    { q: "Welcher Komponist wurde im Laufe seines Lebens taub?", o: ["Mozart", "Bach", "Beethoven", "Chopin"], c: 2 },
    { q: "Welches Tier hat den längsten Hals?", o: ["Strauß", "Giraffe", "Lama", "Kamel"], c: 1 },
    { q: "Wie viele Kontinente gibt es?", o: ["5", "6", "7", "8"], c: 2 },
    { q: "Welches Metall ist bei Raumtemperatur flüssig?", o: ["Blei", "Quecksilber", "Zinn", "Zink"], c: 1 },
    { q: "Wer malte die Mona Lisa?", o: ["Michelangelo", "Raffael", "Leonardo da Vinci", "Donatello"], c: 2 },
    { q: "Welches ist das kleinste Land der Welt?", o: ["Monaco", "Vatikanstadt", "San Marino", "Liechtenstein"], c: 1 },
    { q: "Wie heißt die Hauptstadt von Kanada?", o: ["Toronto", "Vancouver", "Montreal", "Ottawa"], c: 3 },
    { q: "Welches Gas atmen Pflanzen bei der Photosynthese ein?", o: ["Sauerstoff", "Stickstoff", "Kohlendioxid", "Wasserstoff"], c: 2 },
    { q: "Wie viele Planeten hat unser Sonnensystem?", o: ["7", "8", "9", "10"], c: 1 },
    { q: "Welcher Kontinent ist flächenmäßig der größte?", o: ["Afrika", "Nordamerika", "Asien", "Europa"], c: 2 },
    { q: "Wie viele Tage hat ein Jahr?", o: ["360", "364", "365", "366"], c: 2 },
    { q: "Welches Land ist bekannt für die Pyramiden von Gizeh?", o: ["Mexiko", "Ägypten", "Peru", "Sudan"], c: 1 },
    { q: "Welche Nationalität hatte Albert Einstein bei seiner Geburt?", o: ["Schweizer", "Österreicher", "Deutscher", "Amerikaner"], c: 2 },
    { q: "Wie viele Beine hat eine Spinne?", o: ["6", "8", "10", "12"], c: 1 },
    { q: "Wie heißt der längste Fluss Deutschlands (innerhalb der Grenzen)?", o: ["Donau", "Elbe", "Rhein", "Main"], c: 2 },
    { q: "In welchem Land liegt Machu Picchu?", o: ["Chile", "Bolivien", "Peru", "Ecuador"], c: 2 },
    { q: "Welche Blutgruppe gilt als Universalspender?", o: ["A negativ", "B positiv", "AB positiv", "0 negativ"], c: 3 },
    { q: "Was ist die Hauptstadt der Türkei?", o: ["Istanbul", "Ankara", "Izmir", "Antalya"], c: 1 },
    { q: "Wie viele Ringe hat das olympische Symbol?", o: ["4", "5", "6", "7"], c: 1 },
    { q: "Wie viele Stunden hat ein Tag?", o: ["12", "24", "36", "48"], c: 1 },
    { q: "Wer schrieb \"Faust\"?", o: ["Schiller", "Goethe", "Lessing", "Heine"], c: 1 },
    { q: "Welches Tier ist das größte auf der Erde?", o: ["Elefant", "Blauwal", "Giraffe", "Weißer Hai"], c: 1 },
    { q: "In welchem Jahr begann der Zweite Weltkrieg?", o: ["1914", "1933", "1939", "1945"], c: 2 },
    { q: "Wie heißt die Hauptstadt von Spanien?", o: ["Barcelona", "Sevilla", "Madrid", "Valencia"], c: 2 },
    { q: "Wie viele Sekunden hat eine Minute?", o: ["30", "60", "90", "100"], c: 1 },
    { q: "Welcher Planet ist der Sonne am nächsten?", o: ["Venus", "Merkur", "Erde", "Mars"], c: 1 },
    { q: "Welches Tier legt Eier?", o: ["Wal", "Fledermaus", "Schnabeltier", "Delfin"], c: 2 },
    { q: "Wie heißt das größte Wüstengebiet der Welt (ohne Polarwüsten)?", o: ["Gobi", "Kalahari", "Sahara", "Atacama"], c: 2 },
    { q: "Wer erfand die Glühbirne (am bekanntesten)?", o: ["Tesla", "Edison", "Bell", "Marconi"], c: 1 },
    { q: "Was ist die Hauptstadt von Italien?", o: ["Mailand", "Neapel", "Rom", "Florenz"], c: 2 },
    { q: "Wie viele Farben hat die deutsche Flagge?", o: ["2", "3", "4", "5"], c: 1 },
    { q: "Aus welchen Tieren wird Kaschmirwolle gewonnen?", o: ["Schafe", "Ziegen", "Alpakas", "Kamele"], c: 1 },
    { q: "Wie heißt das Haus in Harry Potter, in das Harry kommt?", o: ["Slytherin", "Ravenclaw", "Hufflepuff", "Gryffindor"], c: 3 },
    { q: "Welcher Vogel ist das Wappentier Deutschlands?", o: ["Adler", "Falke", "Rabe", "Storch"], c: 0 },
    { q: "Was ist der pH-Wert von reinem Wasser?", o: ["5", "7", "9", "11"], c: 1 },
    { q: "Welche Stadt wird die \"Ewige Stadt\" genannt?", o: ["Athen", "Rom", "Jerusalem", "Istanbul"], c: 1 },
    { q: "Wie viele Knochen hat ein Erwachsener?", o: ["186", "196", "206", "216"], c: 2 },
    { q: "Wie viele Spieler hat ein Eishockey-Team auf dem Eis (mit Torwart)?", o: ["5", "6", "7", "8"], c: 1 },
    { q: "Welche Programmiersprache wird oft für Webseiten-Interaktivität genutzt?", o: ["Python", "JavaScript", "C", "Java"], c: 1 },
    { q: "Welcher Ozean liegt zwischen Europa und Amerika?", o: ["Pazifik", "Atlantik", "Indischer Ozean", "Nordpolarmeer"], c: 1 },
    { q: "Wie viele Karten hat ein Pokerdeck ohne Joker?", o: ["32", "48", "52", "54"], c: 2 },
    { q: "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", o: ["Willy Brandt", "Konrad Adenauer", "Helmut Schmidt", "Ludwig Erhard"], c: 1 },
    { q: "Wie heißt die Hauptstadt von Frankreich?", o: ["Lyon", "Marseille", "Nizza", "Paris"], c: 3 },
    { q: "Welche Frucht ist die Grundlage von Wein?", o: ["Apfel", "Traube", "Birne", "Pflaume"], c: 1 },
    { q: "Aus welchem Land kommt IKEA?", o: ["Norwegen", "Dänemark", "Schweden", "Finnland"], c: 2 },
    { q: "Welches Instrument hat 88 Tasten?", o: ["Orgel", "Akkordeon", "Klavier", "Keyboard"], c: 2 },
    { q: "Welche Stadt ist die Hauptstadt von Portugal?", o: ["Porto", "Lissabon", "Faro", "Coimbra"], c: 1 },
    { q: "Was ist die kleinste Einheit eines Elements?", o: ["Molekül", "Atom", "Zelle", "Neutron"], c: 1 },
    { q: "Wer gilt als Erfinder des Automobils?", o: ["Daimler", "Benz", "Diesel", "Porsche"], c: 1 },
    { q: "Welches Tier ist das Symbol der WWF?", o: ["Tiger", "Panda", "Elefant", "Delfin"], c: 1 },
    { q: "Wie viele Zähne hat ein Mensch im Milchgebiss?", o: ["16", "20", "24", "28"], c: 1 },
    { q: "Wie heißt der berühmte Uhrturm in London?", o: ["Big Ben", "Tower Bridge", "London Eye", "Westminster"], c: 0 },
    { q: "Welche Sprache wird in Brasilien gesprochen?", o: ["Spanisch", "Portugiesisch", "Brasilianisch", "Italienisch"], c: 1 },
    { q: "Wie heißt der Erfinder der Relativitätstheorie?", o: ["Newton", "Einstein", "Bohr", "Hawking"], c: 1 },
    { q: "Welche Stadt liegt an der Themse?", o: ["Manchester", "London", "Dublin", "Edinburgh"], c: 1 },
    { q: "Wie viele Nullen hat eine Million?", o: ["5", "6", "7", "9"], c: 1 },
    { q: "Welche Band sang \"Bohemian Rhapsody\"?", o: ["The Beatles", "Queen", "Led Zeppelin", "Pink Floyd"], c: 1 },
    { q: "Welches Land hat die Form eines Stiefels?", o: ["Griechenland", "Spanien", "Italien", "Portugal"], c: 2 },
    { q: "Wie heißt der Hauptcharakter in \"Der Herr der Ringe\", der den Ring trägt?", o: ["Sam", "Gandalf", "Frodo", "Aragorn"], c: 2 },
    { q: "Welches ist das häufigste Element im Universum?", o: ["Sauerstoff", "Kohlenstoff", "Wasserstoff", "Helium"], c: 2 },
    { q: "Was ist die Hauptstadt von Österreich?", o: ["Salzburg", "Graz", "Wien", "Innsbruck"], c: 2 },
    { q: "Wie viele Farben hat ein Regenbogen?", o: ["5", "6", "7", "8"], c: 2 },
    { q: "Wie heißt das erste Element im Periodensystem?", o: ["Helium", "Wasserstoff", "Lithium", "Sauerstoff"], c: 1 },
    { q: "Aus welchem Land kommt der Whisky \"Scotch\"?", o: ["Irland", "Schottland", "USA", "Kanada"], c: 1 },
    { q: "Welcher Muskel ist der stärkste im Körper (bezogen auf Kraft)?", o: ["Bizeps", "Kaumuskel", "Oberschenkel", "Herz"], c: 1 },
    { q: "Wer schrieb \"Romeo und Julia\"?", o: ["Dickens", "Shakespeare", "Byron", "Wilde"], c: 1 },
    { q: "Wie heißt die Hauptstadt der Niederlande?", o: ["Rotterdam", "Den Haag", "Amsterdam", "Utrecht"], c: 2 },
    { q: "Welche Farbe hat ein Rubin?", o: ["Blau", "Grün", "Rot", "Gelb"], c: 2 },
    { q: "Welches Tier hat vier Mägen?", o: ["Pferd", "Kuh", "Schwein", "Hund"], c: 1 },
    { q: "Was ist die schnellste Schwimmart?", o: ["Brust", "Rücken", "Schmetterling", "Kraul"], c: 3 },
    { q: "Wie heißt der Gründer von Microsoft?", o: ["Steve Jobs", "Bill Gates", "Elon Musk", "Jeff Bezos"], c: 1 },
    { q: "Welches Land gewann die Fußball-WM 2014?", o: ["Brasilien", "Argentinien", "Deutschland", "Spanien"], c: 2 },
    { q: "Welcher Planet wird der \"Rote Planet\" genannt?", o: ["Venus", "Mars", "Jupiter", "Saturn"], c: 1 },
    { q: "Wie viele Ecken hat ein Hexagon?", o: ["5", "6", "7", "8"], c: 1 },
    { q: "Welche Stadt ist die Hauptstadt von Bayern?", o: ["Nürnberg", "Augsburg", "München", "Regensburg"], c: 2 },
    { q: "Wie viele Jahre dauert eine Legislaturperiode des Bundestags?", o: ["3", "4", "5", "6"], c: 1 },
    { q: "Welcher Käse hat Löcher?", o: ["Gouda", "Emmentaler", "Brie", "Camembert"], c: 1 },
    { q: "Was ist das Gegenteil von Ebbe?", o: ["Strömung", "Welle", "Flut", "Gezeiten"], c: 2 },
    { q: "Wie heißt das berühmte Opernhaus in Sydney?", o: ["Sydney Hall", "Sydney Opera House", "Harbour Opera", "Royal Opera"], c: 1 },
    { q: "Welcher Vogel ist der größte der Welt?", o: ["Albatros", "Kondor", "Strauß", "Emu"], c: 2 },
    { q: "Wie heißt das Mittelmeer auf Englisch?", o: ["Middle Sea", "Mediterranean Sea", "Central Sea", "Medium Sea"], c: 1 },
    { q: "Aus welchem Land stammt Sushi?", o: ["China", "Korea", "Japan", "Thailand"], c: 2 },
    { q: "Wie viele Herzkammern hat ein Mensch?", o: ["2", "3", "4", "5"], c: 2 },
    { q: "Was bedeutet \"www\" im Internet?", o: ["World Wide Web", "Web World Wide", "Wide World Web", "World Web Wide"], c: 0 },
    { q: "Wie heißt der Planet mit den auffälligsten Ringen?", o: ["Jupiter", "Saturn", "Uranus", "Neptun"], c: 1 },
    { q: "Welche Stadt ist die Hauptstadt von Griechenland?", o: ["Thessaloniki", "Athen", "Patras", "Kreta"], c: 1 },
    { q: "Welches Tier ist das nationale Symbol Kanadas?", o: ["Bär", "Elch", "Biber", "Adler"], c: 2 },
    { q: "Wie viele Sekunden hat eine Stunde?", o: ["600", "1800", "3600", "7200"], c: 2 },
    { q: "Welches ist das kleinste Bundesland Deutschlands (Fläche)?", o: ["Saarland", "Bremen", "Hamburg", "Berlin"], c: 1 },
    { q: "Wie nennt man ein Tier, das Fleisch und Pflanzen frisst?", o: ["Herbivore", "Karnivore", "Omnivore", "Insektivore"], c: 2 },
    { q: "Wer sang \"Thriller\"?", o: ["Prince", "Michael Jackson", "Elvis Presley", "Stevie Wonder"], c: 1 },
    { q: "Wie heißt die Hauptstadt von Polen?", o: ["Krakau", "Danzig", "Warschau", "Breslau"], c: 2 },
    { q: "Was misst ein Thermometer?", o: ["Luftdruck", "Temperatur", "Feuchtigkeit", "Windstärke"], c: 1 },
    { q: "Welches Tier ist der Kabeljau?", o: ["Vogel", "Fisch", "Säugetier", "Reptil"], c: 1 },
    { q: "Wie viele Buchstaben hat das deutsche Alphabet (ohne Umlaute)?", o: ["24", "25", "26", "27"], c: 2 },
    { q: "Welche Sportart spielt man in Wimbledon?", o: ["Golf", "Tennis", "Cricket", "Polo"], c: 1 },
    { q: "Wie heißt der Prozess, bei dem Wasser zu Dampf wird?", o: ["Kondensation", "Verdunstung", "Erstarrung", "Sublimation"], c: 1 },
    { q: "Wer war der erste Mensch im Weltall?", o: ["Neil Armstrong", "Juri Gagarin", "Buzz Aldrin", "John Glenn"], c: 1 },
    { q: "Wie heißt die Hauptstadt von Ägypten?", o: ["Alexandria", "Kairo", "Luxor", "Gizeh"], c: 1 },
    { q: "Welches Tier gilt als \"König der Tiere\"?", o: ["Tiger", "Bär", "Löwe", "Elefant"], c: 2 },
    { q: "Was ist die Hauptzutat von Hummus?", o: ["Linsen", "Kichererbsen", "Bohnen", "Erbsen"], c: 1 },
    { q: "Welche Stadt beherbergt den Louvre?", o: ["London", "Rom", "Paris", "Madrid"], c: 2 },
    { q: "Welcher Planet hat den kürzesten Tag?", o: ["Erde", "Mars", "Jupiter", "Venus"], c: 2 },
    { q: "Was ist die Hauptstadt der Schweiz (de facto)?", o: ["Zürich", "Genf", "Bern", "Basel"], c: 2 },
    { q: "Wie viele Punkte hat ein Touchdown im American Football?", o: ["3", "6", "7", "10"], c: 1 },
    { q: "Welche Stadt wird \"Big Apple\" genannt?", o: ["Los Angeles", "Chicago", "New York", "Boston"], c: 2 },
    { q: "In welchem Jahr wurde die Bundesrepublik Deutschland gegründet?", o: ["1945", "1949", "1955", "1961"], c: 1 },
    { q: "Was ist die Hauptstadt von Schweden?", o: ["Göteborg", "Malmö", "Stockholm", "Uppsala"], c: 2 },
    { q: "Welche Farbe hat die Haut eines Zebras unter dem Fell?", o: ["Weiß", "Schwarz", "Grau", "Rosa"], c: 1 },
    { q: "Aus welchem Material besteht die Freiheitsstatue hauptsächlich?", o: ["Bronze", "Kupfer", "Stahl", "Eisen"], c: 1 },
    { q: "Welcher Fluss fließt durch Wien?", o: ["Rhein", "Donau", "Elbe", "Inn"], c: 1 },
    { q: "Wie heißt der Hund in \"Tim und Struppi\"?", o: ["Idefix", "Struppi", "Bello", "Snoopy"], c: 1 },
    { q: "Welche Sportart betreibt Lewis Hamilton?", o: ["Golf", "Formel 1", "Tennis", "Radsport"], c: 1 },
    { q: "Wie viele Nieren hat ein gesunder Mensch?", o: ["1", "2", "3", "4"], c: 1 },
    { q: "Was ist das größte Organ des Menschen?", o: ["Leber", "Haut", "Lunge", "Darm"], c: 1 },
    { q: "Wie heißt der Nationalfeiertag in Deutschland?", o: ["Tag der Einheit", "Tag der Freiheit", "Tag der Republik", "Tag der Mauer"], c: 0 },
    { q: "In welchem Land steht der Taj Mahal?", o: ["Pakistan", "Indien", "Bangladesch", "Nepal"], c: 1 },
    { q: "Welcher Planet hat die meisten Monde (Stand 2025)?", o: ["Jupiter", "Saturn", "Uranus", "Neptun"], c: 1 },
    { q: "Welches Land hat die längste Küstenlinie?", o: ["Australien", "Russland", "Kanada", "Indonesien"], c: 2 },
    { q: "Wie viele Runden hat ein Boxkampf im Profi-Titelkampf maximal?", o: ["10", "12", "15", "20"], c: 1 },
    { q: "Wie heißt der Erfinder des Telefons (offiziell patentiert)?", o: ["Bell", "Edison", "Reis", "Meucci"], c: 0 },
    { q: "Welche Stadt ist die Hauptstadt von Baden-Württemberg?", o: ["Karlsruhe", "Stuttgart", "Mannheim", "Freiburg"], c: 1 },
    { q: "Was ist Kimchi?", o: ["Suppe", "Fermentiertes Gemüse", "Nudelgericht", "Reisgericht"], c: 1 },
    { q: "Welches Land ist der größte Kaffeeproduzent?", o: ["Kolumbien", "Vietnam", "Brasilien", "Äthiopien"], c: 2 },
    { q: "Welche Farbe hat das Trikot des Gesamtführenden bei der Tour de France?", o: ["Grün", "Gelb", "Weiß", "Rot"], c: 1 },
    { q: "Wie viele Tage hat der September?", o: ["28", "29", "30", "31"], c: 2 },
    { q: "Welcher Planet ist der Erde am ähnlichsten in der Größe?", o: ["Mars", "Venus", "Merkur", "Pluto"], c: 1 },
    { q: "Was ist die größte Insel der Welt?", o: ["Grönland", "Madagaskar", "Borneo", "Neuguinea"], c: 0 },
    { q: "Wer war Bundeskanzlerin von 2005 bis 2021?", o: ["Angela Merkel", "Ursula von der Leyen", "Annalena Baerbock", "Sahra Wagenknecht"], c: 0 },
    { q: "Wie viele Prozent Alkohol hat Bier ungefähr?", o: ["2", "5", "10", "15"], c: 1 },
    { q: "Wie heißt das Fest zum Ende der Fastenzeit im Islam?", o: ["Zuckerfest", "Opferfest", "Ramadan", "Nouruz"], c: 0 },
    { q: "Was ist Bitcoin?", o: ["Aktie", "Kryptowährung", "Bank", "Kreditkarte"], c: 1 },
    { q: "Welcher deutsche Fußballverein hat die meisten Meistertitel?", o: ["Borussia Dortmund", "Bayern München", "1. FC Nürnberg", "Hamburger SV"], c: 1 },
    { q: "Wie heißt der Vulkan auf Sizilien?", o: ["Vesuv", "Ätna", "Stromboli", "Pinatubo"], c: 1 },
    { q: "Wie viele Erdteile berührt Russland?", o: ["1", "2", "3", "4"], c: 1 },
    { q: "Wie viele Saiten hat eine Violine?", o: ["3", "4", "5", "6"], c: 1 },
    { q: "Welche Firma stellt das iPhone her?", o: ["Samsung", "Google", "Apple", "Huawei"], c: 2 },
    { q: "Welches Tier ist das Maskottchen von Linux?", o: ["Pinguin", "Fuchs", "Eule", "Elefant"], c: 0 },
    { q: "Wie heißt der Fluss, der durch Paris fließt?", o: ["Loire", "Rhône", "Seine", "Garonne"], c: 2 },
    { q: "Was bedeutet \"carpe diem\"?", o: ["Nutze den Tag", "Liebe das Leben", "Vergiss die Zeit", "Fürchte nichts"], c: 0 },
    { q: "Welche Stadt ist die Hauptstadt von Norwegen?", o: ["Bergen", "Oslo", "Trondheim", "Stavanger"], c: 1 },
    { q: "Welcher Vogel legt die größten Eier?", o: ["Albatros", "Strauß", "Adler", "Pelikan"], c: 1 },
    { q: "Aus wie vielen Sternen besteht der \"Große Wagen\"?", o: ["5", "6", "7", "8"], c: 2 },
    { q: "Welches Getränk enthält Koffein?", o: ["Cola", "Milch", "Orangensaft", "Wasser"], c: 0 },
    { q: "Wie viele Sitze hat ein Fahrrad normalerweise?", o: ["1", "2", "3", "4"], c: 0 },
    { q: "Wie heißt das Sternbild mit dem Gürtel aus drei Sternen?", o: ["Orion", "Cassiopeia", "Löwe", "Skorpion"], c: 0 },
    { q: "Welches Land hat drei Hauptstädte?", o: ["Südafrika", "Australien", "Kanada", "Brasilien"], c: 0 },
    { q: "Welche Stadt ist die Hauptstadt von Dänemark?", o: ["Aarhus", "Odense", "Kopenhagen", "Aalborg"], c: 2 },
    { q: "Wie heißt der Hauptstern unseres Sonnensystems?", o: ["Sirius", "Sonne", "Polaris", "Vega"], c: 1 },
    { q: "Was ist Tofu?", o: ["Fisch", "Sojaprodukt", "Käse", "Getreide"], c: 1 },
    { q: "Welche Stadt hat die meisten Einwohner in Deutschland?", o: ["Hamburg", "München", "Berlin", "Köln"], c: 2 },
    { q: "Wie viele Ecken hat ein Dreieck?", o: ["2", "3", "4", "5"], c: 1 },
    { q: "Welcher Tag ist Weihnachten in Deutschland (Heiligabend)?", o: ["24. Dezember", "25. Dezember", "26. Dezember", "31. Dezember"], c: 0 },
    { q: "Wie heißt der Erfinder des Buchdrucks mit beweglichen Lettern in Europa?", o: ["Luther", "Gutenberg", "Kepler", "Kopernikus"], c: 1 },
    { q: "Wie viele Prozent der Luft sind Sauerstoff ungefähr?", o: ["21", "50", "78", "90"], c: 0 },
    { q: "Welcher Planet ist am weitesten von der Sonne entfernt?", o: ["Uranus", "Saturn", "Neptun", "Jupiter"], c: 2 },
    { q: "Welche Sportart hat die Positionen \"Libero\" und \"Zuspieler\"?", o: ["Handball", "Volleyball", "Basketball", "Wasserball"], c: 1 },
    { q: "Wer hat \"Die Verwandlung\" geschrieben?", o: ["Kafka", "Mann", "Hesse", "Brecht"], c: 0 },
    { q: "Was ist die Hauptstadt von Irland?", o: ["Belfast", "Cork", "Dublin", "Galway"], c: 2 },
    { q: "Welche Zahl ist eine Primzahl?", o: ["9", "15", "17", "21"], c: 2 },
    { q: "Wie viele Weltmeistertitel hat Deutschland im Männerfußball?", o: ["3", "4", "5", "6"], c: 1 },
    { q: "Welches Tier ist Nemo im Film \"Findet Nemo\"?", o: ["Clownfisch", "Doktorfisch", "Goldfisch", "Kugelfisch"], c: 0 },
    { q: "Welche Stadt ist die Hauptstadt von Belgien?", o: ["Antwerpen", "Brüssel", "Gent", "Brügge"], c: 1 },
    { q: "Welches Element hat das chemische Symbol Fe?", o: ["Fluor", "Eisen", "Francium", "Fermium"], c: 1 },
    { q: "Welche Sprache spricht man in Argentinien?", o: ["Portugiesisch", "Spanisch", "Italienisch", "Englisch"], c: 1 },
    { q: "Welcher Vogel spricht nach?", o: ["Papagei", "Taube", "Amsel", "Spatz"], c: 0 },
    { q: "Wie heißt das längste Gebirge der Welt?", o: ["Alpen", "Himalaya", "Anden", "Rocky Mountains"], c: 2 },
    { q: "Wie viele Tore braucht es für einen Hattrick?", o: ["2", "3", "4", "5"], c: 1 },
  ],
};
